In [2]:
from pathlib import Path

import duckdb
import pandas as pd
from tabulate import tabulate

data_root = Path("D:\\데이터\\건축데이터 건축허브 개방데이터")
path_DB = data_root / "건축물대장_2025년_02월.db"

건축허브에서 제공하는 건축물대장 데이터를 활용하여 분석

2025년 2월 이전 데이터는 위반건축물 등 일부 건축물이 빠져있는 문제가 있어 부득이 2025년 2월 말 데이터로 2024년 말 기준 건축물 현황을 집계

In [3]:
# Open a DuckDB connection
con = duckdb.connect(database=path_DB, read_only=True)

# print the list of tables in the database
tables = con.execute("SHOW TABLES").fetchall()
print("Tables in the database:")
for table in tables:
    print(table[0])
    print()

# show heads of the tables
for table in tables:
    table_name = table[0]
    print(f"Head of {table_name}:")
    df = con.execute(f"SELECT * FROM {table_name} LIMIT 5").fetchdf()
    print(df)
    print()

Tables in the database:
기본개요

총괄표제부

층별개요

표제부

Head of 기본개요:
  관리_건축물대장_PK 관리_상위_건축물대장_PK 대장_구분_코드 대장_구분_코드_명 대장_종류_코드 대장_종류_코드_명  \
0      100211           None        1         일반        1      총괄표제부
1      100215           None        1         일반        1      총괄표제부
2      100216           None        1         일반        1      총괄표제부
3      100218           None        1         일반        1      총괄표제부
4      100219           None        1         일반        1      총괄표제부

                  대지_위치                  도로명_대지_위치  건물_명 시군구_코드  ...  \
0  서울특별시 종로구 관철동 12-1번지   서울특별시 종로구 종로14길 20 (관철동)  None  11110  ...
1  서울특별시 종로구 청진동 21-1번지  서울특별시 종로구 종로5길 32-6 (청진동)  None  11110  ...
2  서울특별시 종로구 중학동 16-2번지                       None  None  11110  ...
3  서울특별시 종로구 중학동 24-1번지      서울특별시 종로구 율곡로 5 (중학동)  None  11110  ...
4  서울특별시 종로구 중학동 35-1번지                       None  None  11110  ...

  새주소_지상지하_코드 새주소_본_번 새주소_부_번 지역_코드 지구_코드 구역_코드 지역_코드_명  지구_코드_명 구역_코드_명  \
0           0      20       0  None  None  None    None     None    None
1           0      32       6  None  None  None    None     None    None
2           0    <NA>    <NA>  None  None  None    None     None    None
3           0       5       0  None  None  None    None     None    None
4           0    <NA>    <NA>  None  None  None    None     None    None

      생성_일자
0  20220813
1  20220813
2  20220813
3  20220813
4  20220813

[5 rows x 30 columns]

Head of 총괄표제부:
      관리_건축물대장_PK 대장_구분_코드 대장_구분_코드_명 대장_종류_코드 대장_종류_코드_명 신_구_대장_구분_코드  \
0  10021100218945        2         집합        1      총괄표제부            1
1  10021100219285        1         일반        1      총괄표제부         None
2  10021100218105        2         집합        1      총괄표제부            1
3  10021100218127        2         집합        1      총괄표제부            1
4  10021100218465        1         일반        1      총괄표제부            1

  신_구_대장_구분_코드_명                   대지_위치                도로명_대지_위치  \
0            신대장      서울특별시 종로구 무악동 89번지  서울특별시 종로구 통일로 230 (무악동)
1           None  서울특별시 종로구 누상동 166-84번지                     None
2            신대장   서울특별시 종로구 신영동 211-6번지                     None
3            신대장  서울특별시 종로구 신영동 211-11번지                     None
4            신대장     서울특별시 종로구 종로3가 36번지                     None

                건물_명  ... 허가번호_구분_코드_명 호_수(호) 에너지효율_등급 에너지절감_율 에너지_EPI점수  \
0           경희궁 롯데캐슬  ...         5810     27        1   127.6        87
1               None  ...         None      0     None     0.0         0
2  북악더테라스 월드메르디앙 5단지  ...         1101      0     None     0.0         0
3  북악더테라스 월드메르디앙 2단지  ...         1101      0     None     0.0         0
4               None  ...         None      0     None     0.0         0

  친환경_건축물_등급 친환경_건축물_인증점수 지능형_건축물_등급  지능형_건축물_인증점수     생성_일자
0          2           66       None             0  20220813
1       None            0       None             0  20220813
2       None            0       None             0  20220813
3       None            0       None             0  20220813
4       None            0       None             0  20220813

[5 rows x 64 columns]

Head of 층별개요:
  관리_건축물대장_PK                   대지_위치                   도로명_대지_위치    건물_명  \
0    10021950     서울특별시 종로구 숭인동 201번지                        None    None
1    10021974    서울특별시 종로구 숭인동 1132번지                        None    None
2   100211003  서울특별시 종로구 부암동 129-10번지  서울특별시 종로구 백석동길 304-8 (부암동)  부암스카이빌
3   100211003  서울특별시 종로구 부암동 129-10번지  서울특별시 종로구 백석동길 304-8 (부암동)  부암스카이빌
4   100211003  서울특별시 종로구 부암동 129-10번지  서울특별시 종로구 백석동길 304-8 (부암동)  부암스카이빌

  시군구_코드 법정동_코드 대지_구분_코드     번     지 특수지_명  ...   구조_코드_명     기타_구조 주_용도_코드  \
0  11110  17500        0  0201  0000  None  ...     일반목구조        목조   01001
1  11110  17500        0  1132  0000  None  ...      블록구조     세멘부록조   04999
2  11110  18400        0  0129  0010  None  ...  철근콘크리트구조  철근콘크리트구조   02003
3  11110  18400        0  0129  0010  None  ...  철근콘크리트구조  철근콘크리트구조   02003
4  11110  18400        0  0129  0010  None  ...  철근콘크리트구조  철근콘크리트구조   02003

     주_용도_코드_명        기타_용도   면적(㎡)  주_부속_구분_코드 주_부속_구분_코드_명 면적_제외_여부  \
0         단독주택           주택   29.75           0         주건축물     None
1  기타제2종근린생활시설       근린생활시설   36.26           0         주건축물     None
2        다세대주택  다세대주택 (주차장)  161.89           0         주건축물     None
3        다세대주택        다세대주택  137.95           0         주건축물     None
4        다세대주택        다세대주택  137.95           0         주건축물     None

      생성_일자
0  20220813
1  20220813
2  20220813
3  20220813
4  20220813

[5 rows x 33 columns]

Head of 표제부:
  관리_건축물대장_PK 대장_구분_코드 대장_구분_코드_명 대장_종류_코드 대장_종류_코드_명                  대지_위치  \
0  1028112595        1         일반        2      일반건축물  부산광역시 중구 남포동6가 73-3번지
1  1028112597        1         일반        2      일반건축물  부산광역시 중구 남포동6가 74-1번지
2  1028112613        1         일반        2      일반건축물  부산광역시 중구 남포동6가 78-2번지
3  1028112621        1         일반        2      일반건축물    부산광역시 중구 남포동6가 84번지
4  1028112635        1         일반        2      일반건축물  부산광역시 중구 남포동6가 93-1번지

                    도로명_대지_위치              건물_명 시군구_코드 법정동_코드  ... 에너지효율_등급  \
0  부산광역시 중구 중구로5번길 11 (남포동6가)              None  26110  14100  ...     None
1     부산광역시 중구 구덕로 80 (남포동6가)  남포동6가 74-1 (박상현)  26110  14100  ...     None
2   부산광역시 중구 구덕로 74-1 (남포동6가)            유디치과빌딩  26110  14100  ...     None
3      부산광역시 중구 중구로 3 (남포동6가)              None  26110  14100  ...     None
4   부산광역시 중구 비프광장로 16 (남포동6가)              None  26110  14100  ...     None

  에너지절감_율 에너지_EPI점수 친환경_건축물_등급 친환경_건축물_인증점수 지능형_건축물_등급  지능형_건축물_인증점수  \
0     0.0         0       None            0       None             0
1     0.0         0       None            0       None             0
2     0.0         0       None            0       None             0
3     0.0         0       None            0       None             0
4     0.0         0       None            0       None             0

      생성_일자 내진_설계_적용_여부 내진_능력
0  20221008           0  None
1  20230525           0  None
2  20221008           0  None
3  20221008           0  None
4  20240411           0  None

[5 rows x 77 columns]

In [4]:
# Get the list of tables in the database
tables = con.execute("SHOW TABLES").fetchall()

print("=== COLUMN COUNT SUMMARY ===")
column_counts = []

for table in tables:
    table_name = table[0]
    columns_info = con.execute(f"DESCRIBE {table_name}").fetchdf()
    column_count = len(columns_info)
    column_names = list(columns_info["column_name"])

    column_counts.append(
        {
            "Table Name": table_name,
            "Column Count": column_count,
            "Column Names": ", ".join(column_names),
        }
    )

column_counts_df = pd.DataFrame(column_counts)
# Use context manager to temporarily set pandas display options
with pd.option_context(
    "display.max_columns",
    None,
    "display.max_colwidth",
    None,
    "display.width",
    None,
    "display.max_rows",
    None,
):
    display(column_counts_df)

=== COLUMN COUNT SUMMARY ===

,Table Name,Column Count,Column Names
0,기본개요,30,"관리_건축물대장_PK, 관리_상위_건축물대장_PK, 대장_구분_코드, 대장_구분_코드_명, 대장_종류_코드, 대장_종류_코드_명, 대지_위치, 도로명_대지_위치, 건물_명, 시군구_코드, 법정동_코드, 대지_구분_코드, 번, 지, 특수지_명, 블록, 로트, 외필지_수, 새주소_도로_코드, 새주소_법정동_코드, 새주소_지상지하_코드, 새주소_본_번, 새주소_부_번, 지역_코드, 지구_코드, 구역_코드, 지역_코드_명, 지구_코드_명, 구역_코드_명, 생성_일자"
1,총괄표제부,64,"관리_건축물대장_PK, 대장_구분_코드, 대장_구분_코드_명, 대장_종류_코드, 대장_종류_코드_명, 신_구_대장_구분_코드, 신_구_대장_구분_코드_명, 대지_위치, 도로명_대지_위치, 건물_명, 시군구_코드, 법정동_코드, 대지_구분_코드, 번, 지, 특수지_명, 블록, 로트, 외필지_수, 새주소_도로_코드, 새주소_법정동_코드, 새주소_지상지하_코드, 새주소_본_번, 새주소_부_번, 대지_면적(㎡), 건축_면적(㎡), 건폐_율(%), 연면적(㎡), 용적_률_산정_연면적(㎡), 용적_률(%), 주_용도_코드, 주_용도_코드_명, 기타_용도, 세대_수(세대), 가구_수(가구), 주_건축물_수, 부속_건축물_수, 부속_건축물_면적(㎡), 총_주차_수, 옥내_기계식_대수(대), 옥내_기계식_면적(㎡), 옥외_기계식_대수(대), 옥외_기계식_면적(㎡), 옥내_자주식_대수(대), 옥내_자주식_면적(㎡), 옥외_자주식_대수(대), 옥외_자주식_면적(㎡), 허가_일, 착공_일, 사용승인_일, 허가번호_년, 허가번호_기관_코드, 허가번호_기관_코드_명, 허가번호_구분_코드, 허가번호_구분_코드_명, 호_수(호), 에너지효율_등급, 에너지절감_율, 에너지_EPI점수, 친환경_건축물_등급, 친환경_건축물_인증점수, 지능형_건축물_등급, 지능형_건축물_인증점수, 생성_일자"
2,층별개요,33,"관리_건축물대장_PK, 대지_위치, 도로명_대지_위치, 건물_명, 시군구_코드, 법정동_코드, 대지_구분_코드, 번, 지, 특수지_명, 블록, 로트, 새주소_도로_코드, 새주소_법정동_코드, 새주소_지상지하_코드, 새주소_본_번, 새주소_부_번, 동_명, 층_구분_코드, 층_구분_코드_명, 층_번호, 층_번호_명, 구조_코드, 구조_코드_명, 기타_구조, 주_용도_코드, 주_용도_코드_명, 기타_용도, 면적(㎡), 주_부속_구분_코드, 주_부속_구분_코드_명, 면적_제외_여부, 생성_일자"
3,표제부,77,"관리_건축물대장_PK, 대장_구분_코드, 대장_구분_코드_명, 대장_종류_코드, 대장_종류_코드_명, 대지_위치, 도로명_대지_위치, 건물_명, 시군구_코드, 법정동_코드, 대지_구분_코드, 번, 지, 특수지_명, 블록, 로트, 외필지_수, 새주소_도로_코드, 새주소_법정동_코드, 새주소_지상지하_코드, 새주소_본_번, 새주소_부_번, 동_명, 주_부속_구분_코드, 주_부속_구분_코드_명, 대지_면적(㎡), 건축_면적(㎡), 건폐_율(%), 연면적(㎡), 용적_률_산정_연면적(㎡), 용적_률(%), 구조_코드, 구조_코드_명, 기타_구조, 주_용도_코드, 주_용도_코드_명, 기타_용도, 지붕_코드, 지붕_코드_명, 기타_지붕, 세대_수(세대), 가구_수(가구), 높이(m), 지상_층_수, 지하_층_수, 승용_승강기_수, 비상용_승강기_수, 부속_건축물_수, 부속_건축물_면적(㎡), 총_동_연면적(㎡), 옥내_기계식_대수(대), 옥내_기계식_면적(㎡), 옥외_기계식_대수(대), 옥외_기계식_면적(㎡), 옥내_자주식_대수(대), 옥내_자주식_면적(㎡), 옥외_자주식_대수(대), 옥외_자주식_면적(㎡), 허가_일, 착공_일, 사용승인_일, 허가번호_년, 허가번호_기관_코드, 허가번호_기관_코드_명, 허가번호_구분_코드, 허가번호_구분_코드_명, 호_수(호), 에너지효율_등급, 에너지절감_율, 에너지_EPI점수, 친환경_건축물_등급, 친환경_건축물_인증점수, 지능형_건축물_등급, 지능형_건축물_인증점수, 생성_일자, 내진_설계_적용_여부, 내진_능력"

In [5]:
# Create a list to store the table names and their record counts
table_counts = []

# Iterate through the tables and count the records
for table in tables:
    table_name = table[0]
    count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
    table_counts.append({"Table Name": table_name, "Record Count": count})

# Convert the list to a DataFrame
record_counts_df = pd.DataFrame(table_counts)

# Display the DataFrame
display(record_counts_df)

  Table Name  Record Count
0       기본개요      27994157
1      총괄표제부        615541
2       층별개요      21048715
3        표제부       8027067

In [6]:
table_name = "표제부"


def get_column_counts_duckdb(con: duckdb.DuckDBPyConnection, table_name: str):
    # 0) print the statement
    print(f"Counting columns in table: {table_name}")
    # 1) 테이블 스키마에서 컬럼 이름을 가져오고
    cols_df = con.execute(f"PRAGMA table_info('{table_name}')").fetchdf()
    cols = cols_df["name"].tolist()

    # 2) 각 컬럼에 대한 COUNT 문을 생성
    # 표제부에는 컬럼명에 %가 들어간 경우가 있어, 오류가 발생함
    # 이를 피하기 위해, 컬럼명을 따옴표로 감싸줌
    count_exprs = [f'COUNT("{col}") AS "{table_name}_{col}_count"' for col in cols]

    # 3) 최종 쿼리 조립
    query = """
    SELECT
        {exprs}
    FROM "{table_name}"
    """.format(exprs=",\n    ".join(count_exprs), table_name=table_name)

    # 4) 실행 및 결과 반환
    result = con.execute(query).fetchdf().T

    return result


with pd.option_context("display.max_rows", None, "display.max_columns", None):
    # Display the result with all rows and columns
    print(
        tabulate(get_column_counts_duckdb(con, table_name), intfmt=",", floatfmt=",.0f")
    )

Counting columns in table: 표제부
------------------------------------  ---------
표제부_관리_건축물대장_PK_count       8,027,067
표제부_대장_구분_코드_count           8,027,067
표제부_대장_구분_코드_명_count        8,027,067
표제부_대장_종류_코드_count           8,027,067
표제부_대장_종류_코드_명_count        8,027,067
표제부_대지_위치_count                8,027,067
표제부_도로명_대지_위치_count         7,076,491
표제부_건물_명_count                  1,160,843
표제부_시군구_코드_count              8,027,067
표제부_법정동_코드_count              8,027,063
표제부_대지_구분_코드_count           8,027,059
표제부_번_count                       8,027,067
표제부_지_count                       8,027,055
표제부_특수지_명_count                   33,202
표제부_블록_count                        12,772
표제부_로트_count                         8,734
표제부_외필지_수_count                8,027,067
표제부_새주소_도로_코드_count         7,076,491
표제부_새주소_법정동_코드_count       7,074,579
표제부_새주소_지상지하_코드_count     8,024,683
표제부_새주소_본_번_count             7,174,022
표제부_새주소_부_번_count             5,375,334
표제부_동_명_count                    2,199,542
표제부_주_부속_구분_코드_count        8,027,067
표제부_주_부속_구분_코드_명_count     8,026,468
표제부_대지_면적(㎡)_count            8,027,067
표제부_건축_면적(㎡)_count            8,027,067
표제부_건폐_율(%)_count               8,027,067
표제부_연면적(㎡)_count               8,027,067
표제부_용적_률_산정_연면적(㎡)_count  8,027,067
표제부_용적_률(%)_count               8,027,067
표제부_구조_코드_count                8,006,871
표제부_구조_코드_명_count             8,006,865
표제부_기타_구조_count                7,969,367
표제부_주_용도_코드_count             7,997,938
표제부_주_용도_코드_명_count          7,997,830
표제부_기타_용도_count                7,975,268
표제부_지붕_코드_count                7,989,535
표제부_지붕_코드_명_count             7,989,414
표제부_기타_지붕_count                7,902,619
표제부_세대_수(세대)_count            8,027,067
표제부_가구_수(가구)_count            8,027,067
표제부_높이(m)_count                  8,027,067
표제부_지상_층_수_count               8,027,067
표제부_지하_층_수_count               8,027,067
표제부_승용_승강기_수_count           8,027,067
표제부_비상용_승강기_수_count         8,027,067
표제부_부속_건축물_수_count           8,027,067
표제부_부속_건축물_면적(㎡)_count     8,027,067
표제부_총_동_연면적(㎡)_count         8,027,067
표제부_옥내_기계식_대수(대)_count     8,027,067
표제부_옥내_기계식_면적(㎡)_count     8,027,067
표제부_옥외_기계식_대수(대)_count     8,027,067
표제부_옥외_기계식_면적(㎡)_count     8,027,067
표제부_옥내_자주식_대수(대)_count     8,027,067
표제부_옥내_자주식_면적(㎡)_count     8,027,067
표제부_옥외_자주식_대수(대)_count     8,027,067
표제부_옥외_자주식_면적(㎡)_count     8,027,067
표제부_허가_일_count                  5,323,988
표제부_착공_일_count                  4,150,416
표제부_사용승인_일_count              7,401,141
표제부_허가번호_년_count              2,806,125
표제부_허가번호_기관_코드_count       2,706,819
표제부_허가번호_기관_코드_명_count    2,706,210
표제부_허가번호_구분_코드_count       2,768,162
표제부_허가번호_구분_코드_명_count    2,768,162
표제부_호_수(호)_count                8,027,067
표제부_에너지효율_등급_count             14,863
표제부_에너지절감_율_count            8,027,067
표제부_에너지_EPI점수_count           8,027,067
표제부_친환경_건축물_등급_count          13,596
표제부_친환경_건축물_인증점수_count   8,027,067
표제부_지능형_건축물_등급_count              70
표제부_지능형_건축물_인증점수_count   8,027,067
표제부_생성_일자_count                8,027,067
표제부_내진_설계_적용_여부_count      7,988,748
표제부_내진_능력_count                  425,401
------------------------------------  ---------

In [7]:
table_name = "표제부"
query = f"""SELECT
    *
FROM
    (SUMMARIZE "{table_name}")
WHERE
    column_name IN (
        '시군구_코드',
        '법정동_코드',
        '주_부속_구분_코드',
        '주_부속_구분_코드_명',
        '대지_면적(㎡)',
        '건축_면적(㎡)',
        '건폐_율(%)',
        '연면적(㎡)',
        '용적_률_산정_연면적(㎡)',
        '용적_률(%)',
        '구조_코드',
        '구조_코드_명',
        '기타_구조',
        '주_용도_코드',
        '주_용도_코드_명',
        '기타_용도',
        '높이(m)',
        '지상_층_수',
        '지하_층_수',
        '부속_건축물_수',
        '부속_건축물_면적(㎡)',
        '총_동_연면적(㎡)',
        '허가_일',
        '착공_일',
        '사용승인_일',
    );
"""
con.sql(query).show(max_rows=1_000)

┌─────────────────────────┬───────────────┬─────────────────┬────────────────┬───────────────┬─────────────────────┬────────────────────┬─────────┬─────────┬─────────┬─────────┬─────────────────┐
│       column_name       │  column_type  │       min       │      max       │ approx_unique │         avg         │        std         │   q25   │   q50   │   q75   │  count  │ null_percentage │
│         varchar         │    varchar    │     varchar     │    varchar     │     int64     │       varchar       │      varchar       │ varchar │ varchar │ varchar │  int64  │  decimal(9,2)   │
├─────────────────────────┼───────────────┼─────────────────┼────────────────┼───────────────┼─────────────────────┼────────────────────┼─────────┼─────────┼─────────┼─────────┼─────────────────┤
│ 시군구_코드             │ VARCHAR       │ 0               │ 99999          │           252 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.00 │
│ 법정동_코드             │ VARCHAR       │ 00000           │ 99999          │           881 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.00 │
│ 주_부속_구분_코드       │ VARCHAR       │ 0               │ 1              │             2 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.00 │
│ 주_부속_구분_코드_명    │ VARCHAR       │ 부속건축물      │ 주건축물       │             2 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.01 │
│ 대지_면적(㎡)           │ DECIMAL(18,3) │ 0.000           │ 4333333333.000 │        139670 │ 6725.648867106753   │ 1606405.5985735953 │ 0       │ 114     │ 424     │ 8027067 │            0.00 │
│ 건축_면적(㎡)           │ DECIMAL(18,3) │ -93.660         │ 56237885.000   │        319695 │ 244.79079320466616  │ 35605.07049421027  │ 50      │ 90      │ 159     │ 8027067 │            0.00 │
│ 건폐_율(%)              │ DECIMAL(18,3) │ -31.010         │ 1000000000.000 │         63811 │ 8699.780526720033   │ 2282410.877540149  │ 0       │ 4       │ 35      │ 8027067 │            0.00 │
│ 연면적(㎡)              │ DECIMAL(18,3) │ -132.160        │ 83374375.000   │        492711 │ 638.7323453986369   │ 56449.29007153292  │ 60      │ 117     │ 303     │ 8027067 │            0.00 │
│ 용적_률_산정_연면적(㎡) │ DECIMAL(18,3) │ -132.160        │ 98585340.000   │        426509 │ 561.9911037035072   │ 68400.83814665166  │ 53      │ 104     │ 262     │ 8027067 │            0.00 │
│ 용적_률(%)              │ DECIMAL(18,3) │ -43.760         │ 11314584.000   │        156252 │ 41.700883648784796  │ 4021.4728528495025 │ 0       │ 4       │ 42      │ 8027067 │            0.00 │
│ 구조_코드               │ VARCHAR       │                 │ `              │            43 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.25 │
│ 구조_코드_명            │ VARCHAR       │ 강파이프구조    │ 흙벽돌조       │            43 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.25 │
│ 기타_구조               │ VARCHAR       │ \t 경량철골구조 │ ？조           │        114205 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.72 │
│ 주_용도_코드            │ VARCHAR       │ 000             │ b8990          │           108 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.36 │
│ 주_용도_코드_명         │ VARCHAR       │ 가설건축물      │ 휴양콘도미니엄 │            92 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.36 │
│ 기타_용도               │ VARCHAR       │ \t 공동주택     │ 힐링센터       │        244470 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            0.65 │
│ 높이(m)                 │ DECIMAL(18,3) │ -13.600         │ 88055.000      │         26694 │ 5.720540123933188   │ 123.98012671254581 │ 0       │ 4       │ 8       │ 8027067 │            0.00 │
│ 지상_층_수              │ INTEGER       │ 0               │ 131            │            71 │ 1.9528708306533382  │ 2.6392500255743996 │ 1       │ 1       │ 2       │ 8027067 │            0.00 │
│ 지하_층_수              │ INTEGER       │ -1              │ 93             │            24 │ 0.15861110913861812 │ 0.4228415669057247 │ 0       │ 0       │ 0       │ 8027067 │            0.00 │
│ 부속_건축물_수          │ INTEGER       │ 0               │ 1666           │           115 │ 0.20634323844562405 │ 1.24700571560983   │ 0       │ 0       │ 0       │ 8027067 │            0.00 │
│ 부속_건축물_면적(㎡)    │ DECIMAL(18,3) │ 0.000           │ 320514349.000  │         74878 │ 163.9368843754512   │ 118975.28522327518 │ 0       │ 0       │ 0       │ 8027067 │            0.00 │
│ 총_동_연면적(㎡)        │ DECIMAL(18,3) │ -132.160        │ 568282882.000  │        506857 │ 892.3330412075793   │ 241540.52069360478 │ 47      │ 101     │ 275     │ 8027067 │            0.00 │
│ 허가_일                 │ VARCHAR       │                 │ ㅋ             │         43392 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │           33.67 │
│ 착공_일                 │ VARCHAR       │                 │ 99911111       │         29239 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │           48.29 │
│ 사용승인_일             │ VARCHAR       │                 │ 9990408        │         56445 │ NULL                │ NULL               │ NULL    │ NULL    │ NULL    │ 8027067 │            7.80 │
├─────────────────────────┴───────────────┴─────────────────┴────────────────┴───────────────┴─────────────────────┴────────────────────┴─────────┴─────────┴─────────┴─────────┴─────────────────┤
│ 25 rows                                                                                                                                                                              12 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

표제부 면적 관련 데이터는 미기재율 1% 미만.
그러나 면적, 건폐율, 용적률 등이 음수인 경우, 이론상 100%를 초과할 수 없는 건폐율이 1,000,000,000인 경우 등 이상값 발견됨.

시군구, 법정동, 사용승인일 등은 미기재율은 낮으나 이상값이 발견됨 (0, 99999, 9990408 등)

In [8]:
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    # Display the result with all rows and columns
    print(
        tabulate(
            get_column_counts_duckdb(con, "총괄표제부"), intfmt=",", floatfmt=",.0f"
        )
    )

Counting columns in table: 총괄표제부
----------------------------------------  -------
총괄표제부_관리_건축물대장_PK_count       615,541
총괄표제부_대장_구분_코드_count           615,541
총괄표제부_대장_구분_코드_명_count        615,487
총괄표제부_대장_종류_코드_count           615,541
총괄표제부_대장_종류_코드_명_count        615,541
총괄표제부_신_구_대장_구분_코드_count     613,920
총괄표제부_신_구_대장_구분_코드_명_count  613,920
총괄표제부_대지_위치_count                615,541
총괄표제부_도로명_대지_위치_count         385,698
총괄표제부_건물_명_count                  101,028
총괄표제부_시군구_코드_count              615,540
총괄표제부_법정동_코드_count              615,540
총괄표제부_대지_구분_코드_count           615,540
총괄표제부_번_count                       615,540
총괄표제부_지_count                       615,534
총괄표제부_특수지_명_count                  1,479
총괄표제부_블록_count                         993
총괄표제부_로트_count                         690
총괄표제부_외필지_수_count                615,541
총괄표제부_새주소_도로_코드_count         385,698
총괄표제부_새주소_법정동_코드_count       385,407
총괄표제부_새주소_지상지하_코드_count     609,222
총괄표제부_새주소_본_번_count             417,411
총괄표제부_새주소_부_번_count             294,735
총괄표제부_대지_면적(㎡)_count            615,541
총괄표제부_건축_면적(㎡)_count            615,541
총괄표제부_건폐_율(%)_count               615,541
총괄표제부_연면적(㎡)_count               615,541
총괄표제부_용적_률_산정_연면적(㎡)_count  615,541
총괄표제부_용적_률(%)_count               615,541
총괄표제부_주_용도_코드_count             595,397
총괄표제부_주_용도_코드_명_count          595,389
총괄표제부_기타_용도_count                559,007
총괄표제부_세대_수(세대)_count            615,541
총괄표제부_가구_수(가구)_count            615,541
총괄표제부_주_건축물_수_count             615,541
총괄표제부_부속_건축물_수_count           615,541
총괄표제부_부속_건축물_면적(㎡)_count     615,541
총괄표제부_총_주차_수_count               615,541
총괄표제부_옥내_기계식_대수(대)_count     615,541
총괄표제부_옥내_기계식_면적(㎡)_count     615,541
총괄표제부_옥외_기계식_대수(대)_count     615,541
총괄표제부_옥외_기계식_면적(㎡)_count     615,541
총괄표제부_옥내_자주식_대수(대)_count     615,541
총괄표제부_옥내_자주식_면적(㎡)_count     615,541
총괄표제부_옥외_자주식_대수(대)_count     615,541
총괄표제부_옥외_자주식_면적(㎡)_count     615,541
총괄표제부_허가_일_count                  247,201
총괄표제부_착공_일_count                  231,167
총괄표제부_사용승인_일_count              268,691
총괄표제부_허가번호_년_count              229,816
총괄표제부_허가번호_기관_코드_count       229,590
총괄표제부_허가번호_기관_코드_명_count    229,564
총괄표제부_허가번호_구분_코드_count       230,269
총괄표제부_허가번호_구분_코드_명_count    230,269
총괄표제부_호_수(호)_count                615,541
총괄표제부_에너지효율_등급_count            2,160
총괄표제부_에너지절감_율_count            615,541
총괄표제부_에너지_EPI점수_count           615,541
총괄표제부_친환경_건축물_등급_count         1,883
총괄표제부_친환경_건축물_인증점수_count   615,541
총괄표제부_지능형_건축물_등급_count            13
총괄표제부_지능형_건축물_인증점수_count   615,541
총괄표제부_생성_일자_count                615,541
----------------------------------------  -------

In [9]:
table_name = "총괄표제부"
query = f"""SELECT
    *
FROM
    (SUMMARIZE "{table_name}")
WHERE
    column_name IN (
        '시군구_코드',
        '법정동_코드',
        '주_부속_구분_코드',
        '주_부속_구분_코드_명',
        '대지_면적(㎡)',
        '건축_면적(㎡)',
        '건폐_율(%)',
        '연면적(㎡)',
        '용적_률_산정_연면적(㎡)',
        '용적_률(%)',
        '주_용도_코드',
        '주_용도_코드_명',
        '기타_용도',
        '세대_수(세대)',
        '가구_수(가구)',
        '주_건축물_수',
        '부속_건축물_수',
        '부속_건축물_면적(㎡)',
        '허가_일',
        '착공_일',
        '사용승인_일',
    );
"""
con.sql(query).show(max_rows=1_000)

┌─────────────────────────┬───────────────┬────────────┬─────────────────────────────┬───────────────┬────────────────────┬────────────────────┬─────────┬─────────┬─────────┬────────┬─────────────────┐
│       column_name       │  column_type  │    min     │             max             │ approx_unique │        avg         │        std         │   q25   │   q50   │   q75   │ count  │ null_percentage │
│         varchar         │    varchar    │  varchar   │           varchar           │     int64     │      varchar       │      varchar       │ varchar │ varchar │ varchar │ int64  │  decimal(9,2)   │
├─────────────────────────┼───────────────┼────────────┼─────────────────────────────┼───────────────┼────────────────────┼────────────────────┼─────────┼─────────┼─────────┼────────┼─────────────────┤
│ 시군구_코드             │ VARCHAR       │ 11110      │ 99999                       │           252 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │            0.00 │
│ 법정동_코드             │ VARCHAR       │ 00000      │ 99999                       │           872 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │            0.00 │
│ 대지_면적(㎡)           │ DECIMAL(18,3) │ 0.000      │ 2434234234.000              │         74247 │ 11171.481558528189 │ 3113159.744436616  │ 0       │ 877     │ 2729    │ 615541 │            0.00 │
│ 건축_면적(㎡)           │ DECIMAL(18,3) │ 0.000      │ 104787000.000               │        222777 │ 2033.1001870127254 │ 246797.36364506418 │ 135     │ 287     │ 800     │ 615541 │            0.00 │
│ 건폐_율(%)              │ DECIMAL(18,3) │ 0.000      │ 355805.620                  │         36463 │ 25.03645239715957  │ 483.76973690506924 │ 0       │ 21      │ 38      │ 615541 │            0.00 │
│ 연면적(㎡)              │ DECIMAL(18,3) │ 0.000      │ 3986783503.000              │        259206 │ 19454.93327770855  │ 5390585.676681898  │ 147     │ 355     │ 1119    │ 615541 │            0.00 │
│ 용적_률_산정_연면적(㎡) │ DECIMAL(18,3) │ 0.000      │ 2844507236.000              │        268646 │ 11538.366918890863 │ 3700734.5234395494 │ 142     │ 341     │ 1062    │ 615541 │            0.00 │
│ 용적_률(%)              │ DECIMAL(18,3) │ 0.000      │ 93289180.000                │         50446 │ 197.44058606331666 │ 118919.36409437603 │ 0       │ 25      │ 45      │ 615541 │            0.00 │
│ 주_용도_코드            │ VARCHAR       │ 01000      │ n0300                       │            71 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │            3.27 │
│ 주_용도_코드_명         │ VARCHAR       │ 골프연습장 │ 휴양콘도미니엄              │            55 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │            3.27 │
│ 기타_용도               │ VARCHAR       │ \t 공장    │ ？린생활시설, 위락시설,주택 │         35739 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │            9.18 │
│ 세대_수(세대)           │ INTEGER       │ 0          │ 14308                       │          2131 │ 19.41662537507656  │ 135.09170498804076 │ 0       │ 0       │ 0       │ 615541 │            0.00 │
│ 가구_수(가구)           │ INTEGER       │ 0          │ 1730                        │           210 │ 0.8539544888155297 │ 5.547602567781719  │ 0       │ 0       │ 1       │ 615541 │            0.00 │
│ 주_건축물_수            │ INTEGER       │ 0          │ 98792                       │           298 │ 5.1631800318744    │ 333.64061528472325 │ 2       │ 2       │ 3       │ 615541 │            0.00 │
│ 부속_건축물_수          │ INTEGER       │ 0          │ 20000                       │           103 │ 0.6640256294869067 │ 34.85371530720467  │ 0       │ 0       │ 0       │ 615541 │            0.00 │
│ 부속_건축물_면적(㎡)    │ DECIMAL(18,3) │ 0.000      │ 629634307.000               │         48689 │ 2765.2907154129457 │ 894312.8829532793  │ 0       │ 0       │ 0       │ 615541 │            0.00 │
│ 허가_일                 │ VARCHAR       │            │ 98  1231                    │         15206 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │           59.84 │
│ 착공_일                 │ VARCHAR       │            │ 99  1115                    │         12350 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │           62.44 │
│ 사용승인_일             │ VARCHAR       │  1960505   │ 99  1129                    │         14017 │ NULL               │ NULL               │ NULL    │ NULL    │ NULL    │ 615541 │           56.35 │
├─────────────────────────┴───────────────┴────────────┴─────────────────────────────┴───────────────┴────────────────────┴────────────────────┴─────────┴─────────┴─────────┴────────┴─────────────────┤
│ 19 rows                                                                                                                                                                                    12 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [10]:
query = """
SELECT 
    m.관리_건축물대장_PK, 
    m.관리_상위_건축물대장_PK,
    m.관리_상위_건축물대장_PK IS NULL AS 관리_상위_건축물대장_PK_null,
    m.대지_위치,
    m.건물_명,
    b.동_명,
    b."시군구_코드",
    b."법정동_코드",
    b."주_부속_구분_코드",
    b."주_부속_구분_코드_명",
    b."대지_면적(㎡)",
    b."건축_면적(㎡)",
    b."건폐_율(%)",
    b."연면적(㎡)",
    b."용적_률_산정_연면적(㎡)",
    b."용적_률(%)",
    b."주_용도_코드",
    b."주_용도_코드_명",
    b."기타_용도",
    b."높이(m)",
    b."지상_층_수",
    b."지하_층_수",
    b."부속_건축물_수",
    b."부속_건축물_면적(㎡)",
    b."총_동_연면적(㎡)",
    b."허가_일",
    b."착공_일",
    b."사용승인_일",
    b.생성_일자,
    r."대지_면적(㎡)"               AS "총괄_대지_면적(㎡)",
    r."건축_면적(㎡)"               AS "총괄_건축_면적(㎡)",
    r."건폐_율(%)"                  AS "총괄_건폐_율(%)",
    r."연면적(㎡)"                  AS "총괄_연면적(㎡)",
    r."용적_률_산정_연면적(㎡)"     AS "총괄_용적_률_산정_연면적(㎡)",
    r."용적_률(%)"                  AS "총괄_용적_률(%)",
    r."주_용도_코드"                AS "총괄_주_용도_코드",
    r."주_용도_코드_명"             AS "총괄_주_용도_코드_명",
    r."기타_용도"                   AS "총괄_기타_용도",
    r."세대_수(세대)"               AS "총괄_세대_수(세대)",
    r."가구_수(가구)"               AS "총괄_가구_수(가구)",
    r."주_건축물_수"                AS "총괄_주_건축물_수",
    r."부속_건축물_수"              AS "총괄_부속_건축물_수",
    r."부속_건축물_면적(㎡)"        AS "총괄_부속_건축물_면적(㎡)",
FROM 기본개요 m
INNER JOIN 표제부 b
ON m.관리_건축물대장_PK = b.관리_건축물대장_PK
LEFT JOIN 총괄표제부 r  -- short for "recap"
ON m.관리_상위_건축물대장_PK = r.관리_건축물대장_PK
"""
기본개요_표제부_총괄표제부 = con.sql(query)
기본개요_표제부_총괄표제부.limit(5).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────┬──────────────────────────────────┬──────────────┬─────────────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬─────────────────┬─────────────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬──────────┬──────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬────────────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │            대지_위치             │   건물_명    │      동_명      │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │ 주_용도_코드_명 │        기타_용도        │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일  │ 착공_일  │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │     총괄_기타_용도     │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│      varchar       │         varchar         │           boolean            │             varchar              │   varchar    │     varchar     │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │     varchar     │         varchar         │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar  │ varchar  │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │        varchar         │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────┼─────────────────────────┼──────────────────────────────┼──────────────────────────────────┼──────────────┼─────────────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼─────────────────┼─────────────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼──────────┼──────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼────────────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 1073114451         │ 10731487                │ false                        │ 대전광역시 서구 탄방동 1084번지  │ NULL         │ NULL            │ 30170       │ 10600       │ 0                 │ 주건축물             │         0.000 │      3562.000 │         0.000 │      8135.190 │                4574.200 │         0.000 │ 27000        │ 관광휴게시설    │ 관광휴게시설,노유자시설 │         0.000 │          3 │          1 │              0 │                0.000 │         8135.190 │ 19960203 │ NULL     │ 19961007    │ 20220723  │         148587.500 │          11531.380 │           7.760 │       20389.370 │                    15418.840 │          10.380 │ 13000             │ 운동시설             │ NULL                   │                  0 │                  0 │                 3 │                   0 │                     0.000 │
│ 1073114452         │ 10731487                │ false                        │ 대전광역시 서구 탄방동 1084번지  │ NULL         │ 8동(종합체육관) │ 30170       │ 10600       │ 0                 │ 주건축물             │         0.000 │      7835.420 │         0.000 │     12123.620 │               10714.080 │         0.000 │ 13000        │ 운동시설        │ 운동시설, 근린생활시설  │        12.300 │          3 │          1 │              0 │                0.000 │        12123.620 │ 199711   │ 19971205 │ 20020702    │ 20220723  │         148587.500 │          11531.380 │           7.760 │       20389.370 │                    15418.840 │          10.380 │ 13000             │ 운동시설             │ NULL                   │                  0 │                  0 │                 3 │                   0 │                     0.000 │
│ 1073114911         │ 10731488                │ false                        │ 대전광역시 서구 탄방동 69-13번지 │ 한솔빌리지   │ A동             │ 30170       │ 10600       │ 0                 │ 주건축물             │       559.700 │       272.690 │        48.720 │       649.640 │                 649.640 │       160.880 │ 02000        │ 공동주택        │ 다세대주택              │        12.200 │          4 │          0 │              0 │                0.000 │          649.640 │ 19970707 │ 19970813 │ 19980314    │ 20220723  │            559.700 │            545.380 │          97.440 │         941.330 │                      900.460 │         160.880 │ 02000             │ 공동주택             │ 다세대주택, 다세대주택 │                 12 │                  0 │                 2 │                   0 │                     0.000 │
│ 1073114940         │ 10731489                │ false                        │ 대전광역시 서구 탄방동 626번지   │ 개나리아파트 │ 단지내상가      │ 30170       │ 10600       │ 0                 │ 주건축물             │       336.719 │       202.000 │        19.890 │       667.360 │                 394.340 │       179.650 │ 02000        │ 공동주택        │ 상가                    │         8.200 │          2 │          1 │              0 │                0.000 │          667.360 │ 19930216 │ 19930200 │ 19941114    │ 20220723  │          17917.500 │           8868.290 │          49.500 │       39305.660 │                    32341.950 │         180.500 │ 02000             │ 공동주택             │ 아파트, 아파트         │                374 │                  0 │                 7 │                   0 │                     0.000 │
│ 1073114942         │ 10731489                │ false                        │ 대전광역시 서구 탄방동 626번지   │ 개나리아파트 │ 104동           │ 30170       │ 10600       │ 0                 │ 주건축물             │     17917.500 │       853.920 │        19.890 │      4611.800 │                4230.920 │       179.650 │ 02000        │ 공동주택        │ 아파트                  │        30.750 │         11 │          1 │              4 │             4782.110 │         4611.800 │ 19930216 │ 19930200 │ 19941114    │ 20220723  │          17917.500 │           8868.290 │          49.500 │       39305.660 │                    32341.950 │         180.500 │ 02000             │ 공동주택             │ 아파트, 아파트         │                374 │                  0 │                 7 │                   0 │                     0.000 │
└────────────────────┴─────────────────────────┴──────────────────────────────┴──────────────────────────────────┴──────────────┴─────────────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴─────────────────┴─────────────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴──────────┴──────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴────────────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

In [45]:
con.sql("""
        SELECT * 
        FROM 기본개요_표제부_총괄표제부
        WHERE 대지_위치 LIKE '서울특별시 강남구 대치동 500번지' -- AND 동_명 LIKE ''
        """).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────┬──────────────────────────────────┬───────────────────────┬─────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬─────────────────┬───────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬──────────┬─────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │            대지_위치             │        건물_명        │  동_명  │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │ 주_용도_코드_명 │ 기타_용도 │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일  │ 착공_일 │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │ 총괄_기타_용도 │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│      varchar       │         varchar         │           boolean            │             varchar              │        varchar        │ varchar │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │     varchar     │  varchar  │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar  │ varchar │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │    varchar     │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────┼─────────────────────────┼──────────────────────────────┼──────────────────────────────────┼───────────────────────┼─────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼─────────────────┼───────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼──────────┼─────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 10241100181760     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 개포2차우성아파트12동 │ 12      │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │       791.520 │         0.000 │     12130.800 │               11368.800 │         0.000 │ 02000        │ 공동주택        │ 주거시설  │         0.000 │         15 │          1 │              0 │                0.000 │        12130.800 │ 19830607 │ NULL    │ 19841215    │ 20220813  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
│ 10241100181509     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 개포2차우성아파트14동 │ 14      │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │       693.520 │         0.000 │     10832.400 │               10150.800 │         0.000 │ 02000        │ 공동주택        │ 주거시설  │         0.000 │         15 │          1 │              0 │                0.000 │        10832.400 │ 19830607 │ NULL    │ 19841215    │ 20220813  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
│ 10241100181572     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 개포2차우성아파트11동 │ 11      │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │       849.360 │         0.000 │     13194.000 │               12362.400 │         0.000 │ 02000        │ 공동주택        │ 주거시설  │         0.000 │         15 │          1 │              0 │                0.000 │        13194.000 │ 19830607 │ NULL    │ 19841215    │ 20220813  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
│ 10241100181881     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 개포2차우성아파트13동 │ 13      │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │       849.360 │         0.000 │     13194.000 │               12362.400 │         0.000 │ 02000        │ 공동주택        │ 주거시설  │         0.000 │         15 │          1 │              0 │                0.000 │        13194.000 │ 19830607 │ NULL    │ 19841215    │ 20220813  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
│ 10241100181665     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 개포2차우성아파트15동 │ 15      │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │       849.360 │         0.000 │     13194.000 │               12362.400 │         0.000 │ 02000        │ 공동주택        │ 주거시설  │         0.000 │         15 │          1 │              0 │                0.000 │        13194.000 │ 19830607 │ NULL    │ 19841215    │ 20220813  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
│ 10241100181447     │ 10241100198307          │ false                        │ 서울특별시 강남구 대치동 500번지 │ 우성아파트상가        │ 상가    │ 11680       │ 10600       │ 0                 │ 주건축물             │         0.000 │      2040.330 │         0.000 │      9482.350 │                6084.080 │         0.000 │ 07000        │ 판매시설        │ 판매시설  │         0.000 │          3 │          1 │              0 │                0.000 │         9482.350 │ 19830607 │ NULL    │ 19841215    │ 20231214  │              0.000 │              0.000 │           0.000 │       72027.550 │                        0.000 │           0.000 │ 02000             │ 공동주택             │ 공동주택       │                450 │                  0 │                 6 │                   0 │                     0.000 │
└────────────────────┴─────────────────────────┴──────────────────────────────┴──────────────────────────────────┴───────────────────────┴─────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴─────────────────┴───────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴──────────┴─────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

대치동 500번지 개포우성2차 단지는 총괄표제부에 대지면적 0으로 기재되어, 건폐율, 용적률도 0으로 표시됨.
(토지이용계획 상 실제 면적 36,959.8 ㎡)

표제부 대지면적, 건폐율, 용적률도 미기재(빈 칸)가 아니라 0으로 기재되어 있는데, 개방데이터 상에서는 동일하게 0으로 구분할 수 없음.

In [12]:
con.sql("""
        SELECT * 
        FROM 기본개요_표제부_총괄표제부
        WHERE 대지_위치 LIKE '%한솔동 939%' AND 동_명 LIKE '101동'
        """).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────┬───────────────────────────────┬──────────────┬─────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬─────────────────┬──────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬──────────┬──────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬──────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │           대지_위치           │   건물_명    │  동_명  │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │ 주_용도_코드_명 │    기타_용도     │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일  │ 착공_일  │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │  총괄_기타_용도  │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│      varchar       │         varchar         │           boolean            │            varchar            │   varchar    │ varchar │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │     varchar     │     varchar      │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar  │ varchar  │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │     varchar      │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────┼─────────────────────────┼──────────────────────────────┼───────────────────────────────┼──────────────┼─────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼─────────────────┼──────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼──────────┼──────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼──────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 10821100199335     │ 10821100198694          │ false                        │ 세종특별자치시 한솔동 939번지 │ 첫마을아파트 │ 101동   │ 36110       │ 10600       │ 0                 │ 주건축물             │         0.000 │      7235.080 │         0.000 │     23199.060 │               22728.840 │         0.000 │ 02000        │ 공동주택        │ 공동주택(아파트) │        78.500 │         26 │          1 │              0 │                0.000 │        23199.060 │ 20071227 │ 20090331 │ 20111130    │ 20221112  │          69432.000 │          20105.660 │          28.960 │      169706.830 │                   113575.150 │         163.580 │ 02000             │ 공동주택             │ 공동주택(아파트) │                895 │                  0 │                12 │                  16 │                 51765.470 │
└────────────────────┴─────────────────────────┴──────────────────────────────┴───────────────────────────────┴──────────────┴─────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴─────────────────┴──────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴──────────┴──────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴──────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

한솔동 939번지, 101동: 표제부 대장상에서 대지면적, 건폐율, 용적률이 0으로 기재가 아니라 미기재(빈 칸)된 경우.
개방데이터 상에서는 동일하게 0으로 구분할 수 없음.

In [13]:
con.sql("SELECT COUNT(*) FROM 기본개요_표제부_총괄표제부").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      8027067 │
└──────────────┘

In [14]:
query = """
SELECT
  관리_상위_건축물대장_PK_null,
  주_부속_구분_코드,
  COUNT(*) AS 건축물_수,
  AVG("대지_면적(㎡)") AS 평균_대지_면적,
  AVG("건축_면적(㎡)") AS 평균_건축_면적,
  AVG("건폐_율(%)") AS 평균_건폐율,
  AVG("연면적(㎡)") AS 평균_연면적,
  AVG("용적_률_산정_연면적(㎡)") AS 평균_용적률산정용연면적,
  AVG("용적_률(%)") AS 평균_용적률,
  AVG(지상_층_수) AS 평균_지상층수,
  AVG(지하_층_수) AS 평균_지하층수,
  AVG("부속_건축물_수") AS 평균_부속_건축물_수,
  AVG("부속_건축물_면적(㎡)") AS 평균_부속_건축물_면적,
  AVG("총_동_연면적(㎡)") AS 평균_총_동_연면적,
  AVG("총괄_대지_면적(㎡)") AS 평균_총괄_대지_면적,
  AVG("총괄_건축_면적(㎡)") AS 평균_총괄_건축_면적,
  AVG("총괄_건폐_율(%)") AS 평균_총괄_건폐율,
  AVG("총괄_연면적(㎡)") AS 평균_총괄_연면적,
  AVG("총괄_용적_률_산정_연면적(㎡)") AS 평균_총괄_용적률산정용연면적,
  AVG("총괄_용적_률(%)") AS 평균_총괄_용적률,
  AVG("총괄_주_건축물_수") AS 평균_총괄_주_건축물_수,
FROM
  기본개요_표제부_총괄표제부
GROUP BY
  관리_상위_건축물대장_PK_null,
  주_부속_구분_코드
ORDER BY
  관리_상위_건축물대장_PK_null DESC,
  주_부속_구분_코드;
"""
con.sql(query).show()

┌──────────────────────────────┬───────────────────┬───────────┬────────────────────┬────────────────────┬─────────────────────┬────────────────────┬─────────────────────────┬────────────────────┬────────────────────┬──────────────────────┬─────────────────────┬───────────────────────┬────────────────────┬─────────────────────┬─────────────────────┬────────────────────┬───────────────────┬──────────────────────────────┬────────────────────┬────────────────────────┐
│ 관리_상위_건축물대장_PK_null │ 주_부속_구분_코드 │ 건축물_수 │   평균_대지_면적   │   평균_건축_면적   │     평균_건폐율     │    평균_연면적     │ 평균_용적률산정용연면적 │    평균_용적률     │   평균_지상층수    │    평균_지하층수     │ 평균_부속_건축물_수 │ 평균_부속_건축물_면적 │ 평균_총_동_연면적  │ 평균_총괄_대지_면적 │ 평균_총괄_건축_면적 │  평균_총괄_건폐율  │ 평균_총괄_연면적  │ 평균_총괄_용적률산정용연면적 │  평균_총괄_용적률  │ 평균_총괄_주_건축물_수 │
│           boolean            │      varchar      │   int64   │       double       │       double       │       double        │       double       │         double          │       double       │       double       │        double        │       double        │        double         │       double       │       double        │       double        │       double       │      double       │            double            │       double       │         double         │
├──────────────────────────────┼───────────────────┼───────────┼────────────────────┼────────────────────┼─────────────────────┼────────────────────┼─────────────────────────┼────────────────────┼────────────────────┼──────────────────────┼─────────────────────┼───────────────────────┼────────────────────┼─────────────────────┼─────────────────────┼────────────────────┼───────────────────┼──────────────────────────────┼────────────────────┼────────────────────────┤
│ true                         │ 0                 │   5456295 │ 3003.9403603139126 │ 154.57965347639745 │  12797.090682726466 │  405.2405387628418 │      328.07887677169214 │ 57.952869054367476 │ 1.8589106710689214 │  0.17664844001286586 │  0.2056747298304069 │      9.59804529337215 │  602.5216908885975 │                NULL │                NULL │               NULL │              NULL │                         NULL │               NULL │                   NULL │
│ true                         │ 1                 │    420560 │ 18345.457396126592 │ 53.493765824139246 │  1.0739089856381967 │  70.71069069336123 │       61.13110864323759 │ 1.2245358070192125 │ 0.9189009891573141 │ 0.034054593874833554 │ 0.10406838501046224 │    11.680119409834507 │  75.38907850960624 │                NULL │                NULL │               NULL │              NULL │                         NULL │               NULL │                   NULL │
│ false                        │ 0                 │   1908672 │  14285.18333489882 │  542.3962130235053 │    4.44520038277923 │ 1285.7856461461163 │      1383.4731428951648 │  9.346651982111123 │  2.579522306608993 │  0.11420453592864567 │  0.1932123486906079 │    504.49488222806224 │   1796.69360092567 │   36030.23264958943 │   6107.205679887735 │  25.65795188299401 │ 151347.8231477541 │           62830.468271094556 │ 164.19374335335016 │       9.89347083550848 │
│ false                        │ 1                 │    241540 │ 10829.487032201705 │ 263.99811547983774 │ 0.34443115840026495 │ 1789.1622805912064 │       226.6264728409373 │ 0.7168735613148961 │  0.923842841765339 │  0.31893268195743973 │  0.5032831001076427 │    1224.3733594352902 │ 1715.1470529767325 │   45289.38347619843 │   6757.507034711994 │ 25.524779483211177 │ 582046.1124249285 │           362655.84306958225 │  148.8152487084676 │      7.419819471252138 │
└──────────────────────────────┴───────────────────┴───────────┴────────────────────┴────────────────────┴─────────────────────┴────────────────────┴─────────────────────────┴────────────────────┴────────────────────┴──────────────────────┴─────────────────────┴───────────────────────┴────────────────────┴─────────────────────┴─────────────────────┴────────────────────┴───────────────────┴──────────────────────────────┴────────────────────┴────────────────────────┘

총괄표제부가 없는 단독 주건축물에서 평균 건폐율이 13,000%로 나타나는 등, 이상값의 영향이 매우 크다.

In [15]:
query = """
SELECT * FROM 기본개요_표제부_총괄표제부
WHERE
  주_부속_구분_코드 = 0
"""
주건축물 = con.sql(query)
주건축물.limit(5).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────┬──────────────────────────────────┬──────────────┬─────────────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬─────────────────┬─────────────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬──────────┬──────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬────────────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │            대지_위치             │   건물_명    │      동_명      │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │ 주_용도_코드_명 │        기타_용도        │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일  │ 착공_일  │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │     총괄_기타_용도     │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│      varchar       │         varchar         │           boolean            │             varchar              │   varchar    │     varchar     │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │     varchar     │         varchar         │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar  │ varchar  │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │        varchar         │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────┼─────────────────────────┼──────────────────────────────┼──────────────────────────────────┼──────────────┼─────────────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼─────────────────┼─────────────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼──────────┼──────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼────────────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 1073114451         │ 10731487                │ false                        │ 대전광역시 서구 탄방동 1084번지  │ NULL         │ NULL            │ 30170       │ 10600       │ 0                 │ 주건축물             │         0.000 │      3562.000 │         0.000 │      8135.190 │                4574.200 │         0.000 │ 27000        │ 관광휴게시설    │ 관광휴게시설,노유자시설 │         0.000 │          3 │          1 │              0 │                0.000 │         8135.190 │ 19960203 │ NULL     │ 19961007    │ 20220723  │         148587.500 │          11531.380 │           7.760 │       20389.370 │                    15418.840 │          10.380 │ 13000             │ 운동시설             │ NULL                   │                  0 │                  0 │                 3 │                   0 │                     0.000 │
│ 1073114452         │ 10731487                │ false                        │ 대전광역시 서구 탄방동 1084번지  │ NULL         │ 8동(종합체육관) │ 30170       │ 10600       │ 0                 │ 주건축물             │         0.000 │      7835.420 │         0.000 │     12123.620 │               10714.080 │         0.000 │ 13000        │ 운동시설        │ 운동시설, 근린생활시설  │        12.300 │          3 │          1 │              0 │                0.000 │        12123.620 │ 199711   │ 19971205 │ 20020702    │ 20220723  │         148587.500 │          11531.380 │           7.760 │       20389.370 │                    15418.840 │          10.380 │ 13000             │ 운동시설             │ NULL                   │                  0 │                  0 │                 3 │                   0 │                     0.000 │
│ 1073114911         │ 10731488                │ false                        │ 대전광역시 서구 탄방동 69-13번지 │ 한솔빌리지   │ A동             │ 30170       │ 10600       │ 0                 │ 주건축물             │       559.700 │       272.690 │        48.720 │       649.640 │                 649.640 │       160.880 │ 02000        │ 공동주택        │ 다세대주택              │        12.200 │          4 │          0 │              0 │                0.000 │          649.640 │ 19970707 │ 19970813 │ 19980314    │ 20220723  │            559.700 │            545.380 │          97.440 │         941.330 │                      900.460 │         160.880 │ 02000             │ 공동주택             │ 다세대주택, 다세대주택 │                 12 │                  0 │                 2 │                   0 │                     0.000 │
│ 1073114940         │ 10731489                │ false                        │ 대전광역시 서구 탄방동 626번지   │ 개나리아파트 │ 단지내상가      │ 30170       │ 10600       │ 0                 │ 주건축물             │       336.719 │       202.000 │        19.890 │       667.360 │                 394.340 │       179.650 │ 02000        │ 공동주택        │ 상가                    │         8.200 │          2 │          1 │              0 │                0.000 │          667.360 │ 19930216 │ 19930200 │ 19941114    │ 20220723  │          17917.500 │           8868.290 │          49.500 │       39305.660 │                    32341.950 │         180.500 │ 02000             │ 공동주택             │ 아파트, 아파트         │                374 │                  0 │                 7 │                   0 │                     0.000 │
│ 1073114942         │ 10731489                │ false                        │ 대전광역시 서구 탄방동 626번지   │ 개나리아파트 │ 104동           │ 30170       │ 10600       │ 0                 │ 주건축물             │     17917.500 │       853.920 │        19.890 │      4611.800 │                4230.920 │       179.650 │ 02000        │ 공동주택        │ 아파트                  │        30.750 │         11 │          1 │              4 │             4782.110 │         4611.800 │ 19930216 │ 19930200 │ 19941114    │ 20220723  │          17917.500 │           8868.290 │          49.500 │       39305.660 │                    32341.950 │         180.500 │ 02000             │ 공동주택             │ 아파트, 아파트         │                374 │                  0 │                 7 │                   0 │                     0.000 │
└────────────────────┴─────────────────────────┴──────────────────────────────┴──────────────────────────────────┴──────────────┴─────────────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴─────────────────┴─────────────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴──────────┴──────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴────────────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

In [16]:
con.sql("SELECT COUNT(*) FROM 주건축물").show()

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      7364967 │
└──────────────┘

건축물대장 표제부 중, 기본개요와 연계 성공하고, 주/부속 구분 코드가 0(주건축물)으로 기재된 경우는 7,364,967 건으로, 2024년 건축물 현황 통계 7,421,603동과 비교할 때 다소 작은 수치이다.

이러한 차이는 보안시설 등 일부 건축물 데이터가 개방데이터에서 제외된 것이 주 원인으로 판단되나, 기본개요 연계 실패, 주/부속 구분 코드 기재 오류 등의 경우도 배제할 수 없다.

In [17]:
query = """
SELECT * FROM 주건축물
WHERE
  관리_상위_건축물대장_PK_null IS true
"""
주건축물_단독 = con.sql(query)
주건축물_단독.limit(5).show()

┌────────────────────────┬─────────────────────────┬──────────────────────────────┬─────────────────────────────────────────┬─────────┬─────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬───────────────────┬───────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬──────────┬──────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│   관리_건축물대장_PK   │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │                대지_위치                │ 건물_명 │  동_명  │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │  주_용도_코드_명  │     기타_용도     │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일  │ 착공_일  │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │ 총괄_기타_용도 │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│        varchar         │         varchar         │           boolean            │                 varchar                 │ varchar │ varchar │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │      varchar      │      varchar      │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar  │ varchar  │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │    varchar     │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────────┼─────────────────────────┼──────────────────────────────┼─────────────────────────────────────────┼─────────┼─────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼───────────────────┼───────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼──────────┼──────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 1000000000000002117962 │ NULL                    │ true                         │ 전라남도 나주시 노안면 안산리 623번지   │ NULL    │ 주1동   │ 46170       │ 38027       │ 0                 │ 주건축물             │       333.000 │        83.100 │        24.950 │        83.100 │                  83.100 │        24.950 │ 01000        │ 단독주택          │ 단독주택          │         6.100 │          1 │          0 │              0 │                0.000 │           83.100 │ 20200809 │ 20210402 │ 20230719    │ 20230722  │               NULL │               NULL │            NULL │            NULL │                         NULL │            NULL │ NULL              │ NULL                 │ NULL           │               NULL │               NULL │              NULL │                NULL │                      NULL │
│ 1000000000000002117970 │ NULL                    │ true                         │ 전라남도 나주시 노안면 용산리 417-3번지 │ NULL    │ 주1동   │ 46170       │ 38028       │ 0                 │ 주건축물             │       786.000 │       134.330 │        17.090 │       324.940 │                 324.940 │        41.341 │ 04000        │ 제2종근린생활시설 │ 제2종근린생활시설 │        12.300 │          3 │          0 │              0 │                0.000 │          324.940 │ 20210929 │ 20220414 │ 20230717    │ 20230722  │               NULL │               NULL │            NULL │            NULL │                         NULL │            NULL │ NULL              │ NULL                 │ NULL           │               NULL │               NULL │              NULL │                NULL │                      NULL │
│ 1000000000000002217672 │ NULL                    │ true                         │ 전라남도 나주시 송월동 680-14번지       │ NULL    │ NULL    │ 46170       │ 10200       │ 0                 │ 주건축물             │       181.000 │        89.930 │        49.690 │       179.860 │                 179.860 │        99.370 │ 04000        │ 제2종근린생활시설 │ 제2종근린생활시설 │         8.750 │          2 │          0 │              0 │                0.000 │          179.860 │ 20230102 │ 20230413 │ 20230807    │ 20230808  │               NULL │               NULL │            NULL │            NULL │                         NULL │            NULL │ NULL              │ NULL                 │ NULL           │               NULL │               NULL │              NULL │                NULL │                      NULL │
│ 1000000000000002253390 │ NULL                    │ true                         │ 전라남도 나주시 부덕동 452-1번지        │ NULL    │ NULL    │ 46170       │ 12700       │ 0                 │ 주건축물             │      1350.000 │        96.000 │         7.110 │        96.000 │                  96.000 │         7.110 │ 04000        │ 제2종근린생활시설 │ 제2종근린생활시설 │         5.500 │          1 │          0 │              0 │                0.000 │           96.000 │ 20210827 │ 20230428 │ 20230821    │ 20230828  │               NULL │               NULL │            NULL │            NULL │                         NULL │            NULL │ NULL              │ NULL                 │ NULL           │               NULL │               NULL │              NULL │                NULL │                      NULL │
│ 1000000000000002304224 │ NULL                    │ true                         │ 전라남도 나주시 다시면 복암리 538번지   │ NULL    │ NULL    │ 46170       │ 36025       │ 0                 │ 주건축물             │       264.000 │        93.960 │        35.590 │       149.640 │                 149.640 │        56.680 │ 01000        │ 단독주택          │ 단독주택          │         8.100 │          2 │          0 │              0 │                0.000 │          149.640 │ 20221013 │ 20221202 │ 20230831    │ 20230904  │               NULL │               NULL │            NULL │            NULL │                         NULL │            NULL │ NULL              │ NULL                 │ NULL           │               NULL │               NULL │              NULL │                NULL │                      NULL │
└────────────────────────┴─────────────────────────┴──────────────────────────────┴─────────────────────────────────────────┴─────────┴─────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴───────────────────┴───────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴──────────┴──────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

In [18]:
query_columns = """
  관리_건축물대장_PK,
  관리_상위_건축물대장_PK,
  대지_위치,
  건물_명,
  동_명,
  주_부속_구분_코드,
  "대지_면적(㎡)",
  "건축_면적(㎡)",
  "건폐_율(%)",
  "연면적(㎡)",
  "용적_률_산정_연면적(㎡)",
  "용적_률(%)",
  지상_층_수,
  지하_층_수,
  "부속_건축물_수",
  "부속_건축물_면적(㎡)",
  "총_동_연면적(㎡)",
  생성_일자,
"""
query = f"""
SELECT
{query_columns}
FROM
  주건축물_단독
ORDER BY
  RANDOM();
"""
con.sql(query).limit(20).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────────────────────────┬───────────────┬─────────┬───────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬───────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │                    대지_위치                     │    건물_명    │  동_명  │ 주_부속_구분_코드 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 생성_일자 │
│      varchar       │         varchar         │                     varchar                      │    varchar    │ varchar │      varchar      │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │  varchar  │
├────────────────────┼─────────────────────────┼──────────────────────────────────────────────────┼───────────────┼─────────┼───────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼───────────┤
│ 113513518          │ NULL                    │ 강원특별자치도 강릉시 홍제동 111-5번지           │ NULL          │ NULL    │ 0                 │         0.000 │        63.450 │         0.000 │        90.450 │                  90.450 │         0.000 │          2 │          0 │              0 │                0.000 │           90.450 │ 20221112  │
│ 1097120598         │ NULL                    │ 경기도 부천시 원미구 상동 582-10번지             │ NULL          │ NULL    │ 0                 │       198.300 │       115.060 │        58.020 │       338.400 │                 338.400 │       170.650 │          3 │          0 │              0 │                0.000 │            0.000 │ 20231230  │
│ 127017050          │ NULL                    │ 경상남도 하동군 화개면 덕은리 515-2번지          │ NULL          │ NULL    │ 0                 │       775.000 │        54.540 │         7.040 │        54.540 │                  54.540 │         7.040 │          1 │          0 │              0 │                0.000 │           54.540 │ 20221008  │
│ 1205123291         │ NULL                    │ 전라남도 순천시 금곡동 182번지                   │ NULL          │ NULL    │ 0                 │         0.000 │         7.930 │         0.000 │         7.930 │                   7.930 │         0.000 │          1 │          0 │              0 │                0.000 │            7.930 │ 20221008  │
│ 123816144          │ NULL                    │ 대구광역시 군위군 소보면 송원리 52번지           │ NULL          │ NULL    │ 0                 │       301.000 │        60.990 │        20.260 │        60.990 │                  60.990 │        20.260 │          1 │          0 │              0 │                0.000 │           60.990 │ 20221126  │
│ 1116186016         │ NULL                    │ 경기도 용인시 기흥구 청덕동 326-17번지           │ NULL          │ NULL    │ 0                 │         0.000 │        55.380 │         0.000 │        55.380 │                   0.000 │         0.000 │          1 │          0 │              0 │                0.000 │            0.000 │ 20220909  │
│ 1223119015         │ NULL                    │ 전라남도 진도군 조도면 관사도리 250번지          │ NULL          │ NULL    │ 0                 │      1050.000 │        72.400 │         6.900 │        72.400 │                  72.400 │         6.900 │          1 │          0 │              1 │               18.200 │            0.000 │ 20221008  │
│ 1116137232         │ NULL                    │ 경기도 용인시 처인구 백암면 장평리 596-3번지     │ NULL          │ NULL    │ 0                 │       476.000 │        99.420 │        20.880 │       198.840 │                 198.840 │        41.770 │          2 │          0 │              0 │                0.000 │            0.000 │ 20220909  │
│ 107517811          │ NULL                    │ 대전광역시 대덕구 석봉동 423-8번지               │ NULL          │ NULL    │ 0                 │         0.000 │       106.530 │         0.000 │       319.590 │                 319.590 │         0.000 │          3 │          0 │              0 │                0.000 │          319.590 │ 20220723  │
│ 1276129533         │ NULL                    │ 제주특별자치도 제주시 아라이동 1309-3번지        │ NULL          │ NULL    │ 0                 │      3035.000 │        26.520 │         0.870 │        26.520 │                  26.520 │         0.870 │          1 │          0 │              0 │                0.000 │            0.000 │ 20221112  │
│ 1169129172         │ NULL                    │ 충청남도 천안시 동남구 신부동 491-9번지          │ NULL          │ NULL    │ 0                 │         0.000 │        83.450 │         0.000 │       152.600 │                 131.690 │         0.000 │          2 │          1 │              0 │                0.000 │          152.600 │ 20220723  │
│ 104314842          │ NULL                    │ 부산광역시 기장군 기장읍 만화리 45번지           │ NULL          │ NULL    │ 0                 │         0.000 │       101.400 │         0.000 │       101.400 │                 101.400 │         0.000 │          1 │          0 │              1 │               31.500 │            0.000 │ 20221008  │
│ 115716074          │ NULL                    │ 충청북도 충주시 교현동 352-5번지                 │ NULL          │ NULL    │ 0                 │       159.000 │       114.440 │        71.970 │       222.880 │                 222.880 │       140.180 │          2 │          0 │              0 │                0.000 │          222.880 │ 20220924  │
│ 102917912          │ NULL                    │ 부산광역시 서구 서대신동2가 470-11번지           │ 서대2동노인정 │ NULL    │ 0                 │       316.000 │        67.200 │        21.270 │       105.150 │                 105.150 │        33.280 │          2 │          0 │              0 │                0.000 │          105.150 │ 20221008  │
│ 12771100272596     │ NULL                    │ 제주특별자치도 서귀포시 안덕면 사계리 2391-1번지 │ NULL          │ NULL    │ 0                 │       309.000 │        77.640 │        25.120 │       105.540 │                 105.540 │        34.150 │          2 │          0 │              0 │                0.000 │          105.540 │ 20221112  │
│ 1120132167         │ NULL                    │ 경기도 파주시 조리읍 봉일천리 79-49번지          │ NULL          │ NULL    │ 0                 │         0.000 │       160.270 │         0.000 │       160.270 │                 160.270 │         0.000 │          1 │          0 │              0 │                0.000 │          160.270 │ 20220909  │
│ 11571100172936     │ NULL                    │ 충청북도 충주시 봉방동 131-7번지                 │ NULL          │ NULL    │ 0                 │       588.000 │        99.120 │        16.860 │        99.120 │                  99.120 │        16.860 │          1 │          0 │              1 │                7.920 │           99.120 │ 20220924  │
│ 10971100250626     │ NULL                    │ 경기도 부천시 오정구 여월동 44-75번지            │ NULL          │ NULL    │ 0                 │       533.000 │        36.000 │         6.750 │        36.000 │                  36.000 │         6.750 │          1 │          0 │              0 │                0.000 │           36.000 │ 20231230  │
│ 1094115206         │ NULL                    │ 경기도 안양시 만안구 박달동 68-92번지            │ NULL          │ NULL    │ 0                 │         0.000 │         0.000 │         0.000 │       326.620 │                   0.000 │         0.000 │          2 │          1 │              0 │                0.000 │          326.620 │ 20220909  │
│ 103617105          │ NULL                    │ 부산광역시 해운대구 반송동 250-1668번지          │ 우일빌라      │ NULL    │ 0                 │        92.000 │        82.530 │        89.710 │       330.120 │                 330.120 │       358.830 │          4 │          0 │              0 │                0.000 │          330.120 │ 20221008  │
├────────────────────┴─────────────────────────┴──────────────────────────────────────────────────┴───────────────┴─────────┴───────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴───────────┤
│ 20 rows                                                                                                                                                                                                                                                                                                                                       18 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

단독 주건축물의 경우, 대지면적, 건폐율, 용적률에 오류가 있는 경우가 많다.

건축면적, 연면적, 용적률 산정용 연면적, 지상/지하 층수의 오류율이 낮다.

총 동 연면적은 연면적과 동일하거나 0(미기재)인 경우가 많다.

→ 동별 연면적 파악을 위해서는 연면적 값 사용, 검증에는 건축면적, 층수 등 사용

건축면적과 연면적이 0(미기재)인 건축물도 다수 존재. 용적률 산정 연면적만 기재됨.

사용승인일 기준 최근 10년 건축한 건축물의 경우에도 연면적이 음수인 등 오류 사례 존재함.

- 광진리 168-1번지: 신축 내역 없이 -132.16 ㎡ 개축만 등재하여 연면적이 음수로 기재됨
- 서부리 816-18번지: 증축 후 이기된 별도 대장과 별개로 감축만 등재하여 연면적 음수 기재
- 본리리 108-2번지: 2004년 신축 사용승인 후 용도변경, 대장 정비 등 있었으나, 최종적으로 건축면적, 연면적 미기재, 용적률 산정용 연면적 음수 기재. 층별개요는 정상.

여의도 면적(제방 안쪽 면적 2.9㎢ = 2,900,000㎡)의 수 배~수십 배에 달하는 연면적이 기재된 경우 다수로, 대지면적, 건축면적 등과 비교할 때 오류임이 명백함.

연면적이 지나치게 큰 오류가 있는 경우 총 동 연면적도 같은 값이어서 오류 정정에 도움이 되지 않음.

집합건축물대장 표제부의 경우 대지면적, 건폐율, 용적률이 기재되지 않음. 또한, 해당 수치는 대지 단위로 산정되므로 동별 연면적 검증에는 도움이 되지 않음.

건축면적이 미기재된 사례도 있음.

- 한솔동 939번지 상가동: 건축면적 미기재(대장상 빈 칸으로 나타남).
  실제로는 상가동이 독립적으로 존재하는 것이 아니라 101동 하부에 위치하고 있으며,
  주동과 그 사이 공간에 위치한 1층 건물로 옥상을 공원화하여 이용하고 있음.
  실제로 1층 부분이 건축면적에 산입되지 않아 건축면적이 0이 된 것인지는 알 수 없으나,
  건축물대장에서는 빈 칸으로 나타나고 있으므로, 미기재로 판단함.

지상층수가 0으로 기재된 사례가 9,097건에 달함.
다만, 지하도상가 등 실제로 지상층이 존재하지 않는 경우도 포함된 수치임.

지상층수는 0이 반드시 미기재를 뜻하지는 않으므로 주의가 필요함.

## 요약

연면적, 용적률 산정 연면적, 대지면적, 건축면적, 건폐율, 용적률 등 데이터는 미기재를 0으로 저장하고 있음.

이외에도 명백한 오류 사례가 많음.

수치 데이터 미기재(0) 및 오류 사례를 널(null)값으로 처리하고, 검증 규칙을 미기재 및 오류를 고려하여 엄밀하게 정의할 필요가 있음.

---

In [19]:
주건축물.columns

['관리_건축물대장_PK',
 '관리_상위_건축물대장_PK',
 '관리_상위_건축물대장_PK_null',
 '대지_위치',
 '건물_명',
 '동_명',
 '시군구_코드',
 '법정동_코드',
 '주_부속_구분_코드',
 '주_부속_구분_코드_명',
 '대지_면적(㎡)',
 '건축_면적(㎡)',
 '건폐_율(%)',
 '연면적(㎡)',
 '용적_률_산정_연면적(㎡)',
 '용적_률(%)',
 '주_용도_코드',
 '주_용도_코드_명',
 '기타_용도',
 '높이(m)',
 '지상_층_수',
 '지하_층_수',
 '부속_건축물_수',
 '부속_건축물_면적(㎡)',
 '총_동_연면적(㎡)',
 '허가_일',
 '착공_일',
 '사용승인_일',
 '생성_일자',
 '총괄_대지_면적(㎡)',
 '총괄_건축_면적(㎡)',
 '총괄_건폐_율(%)',
 '총괄_연면적(㎡)',
 '총괄_용적_률_산정_연면적(㎡)',
 '총괄_용적_률(%)',
 '총괄_주_용도_코드',
 '총괄_주_용도_코드_명',
 '총괄_기타_용도',
 '총괄_세대_수(세대)',
 '총괄_가구_수(가구)',
 '총괄_주_건축물_수',
 '총괄_부속_건축물_수',
 '총괄_부속_건축물_면적(㎡)']

In [20]:
주건축물.limit(1).show()

┌────────────────────┬─────────────────────────┬──────────────────────────────┬──────────────────────────────────┬──────────┬─────────┬─────────────┬─────────────┬───────────────────┬──────────────────────┬───────────────┬───────────────┬───────────────┬───────────────┬─────────────────────────┬───────────────┬──────────────┬─────────────────┬────────────────────────┬───────────────┬────────────┬────────────┬────────────────┬──────────────────────┬──────────────────┬─────────┬─────────┬─────────────┬───────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬──────────────────────┬────────────────────────────────────────────┬────────────────────┬────────────────────┬───────────────────┬─────────────────────┬───────────────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │ 관리_상위_건축물대장_PK_null │            대지_위치             │ 건물_명  │  동_명  │ 시군구_코드 │ 법정동_코드 │ 주_부속_구분_코드 │ 주_부속_구분_코드_명 │ 대지_면적(㎡) │ 건축_면적(㎡) │  건폐_율(%)   │  연면적(㎡)   │ 용적_률_산정_연면적(㎡) │  용적_률(%)   │ 주_용도_코드 │ 주_용도_코드_명 │       기타_용도        │    높이(m)    │ 지상_층_수 │ 지하_층_수 │ 부속_건축물_수 │ 부속_건축물_면적(㎡) │ 총_동_연면적(㎡) │ 허가_일 │ 착공_일 │ 사용승인_일 │ 생성_일자 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_용도_코드 │ 총괄_주_용도_코드_명 │               총괄_기타_용도               │ 총괄_세대_수(세대) │ 총괄_가구_수(가구) │ 총괄_주_건축물_수 │ 총괄_부속_건축물_수 │ 총괄_부속_건축물_면적(㎡) │
│      varchar       │         varchar         │           boolean            │             varchar              │ varchar  │ varchar │   varchar   │   varchar   │      varchar      │       varchar        │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │ decimal(18,3) │      decimal(18,3)      │ decimal(18,3) │   varchar    │     varchar     │        varchar         │ decimal(18,3) │   int32    │   int32    │     int32      │    decimal(18,3)     │  decimal(18,3)   │ varchar │ varchar │   varchar   │  varchar  │   decimal(18,3)    │   decimal(18,3)    │  decimal(18,3)  │  decimal(18,3)  │        decimal(18,3)         │  decimal(18,3)  │      varchar      │       varchar        │                  varchar                   │       int32        │       int32        │       int32       │        int32        │       decimal(18,3)       │
├────────────────────┼─────────────────────────┼──────────────────────────────┼──────────────────────────────────┼──────────┼─────────┼─────────────┼─────────────┼───────────────────┼──────────────────────┼───────────────┼───────────────┼───────────────┼───────────────┼─────────────────────────┼───────────────┼──────────────┼─────────────────┼────────────────────────┼───────────────┼────────────┼────────────┼────────────────┼──────────────────────┼──────────────────┼─────────┼─────────┼─────────────┼───────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼──────────────────────┼────────────────────────────────────────────┼────────────────────┼────────────────────┼───────────────────┼─────────────────────┼───────────────────────────┤
│ 1024122357         │ 10241394                │ false                        │ 서울특별시 강남구 삼성동 159번지 │ 무역회관 │ NULL    │ 11680       │ 10500       │ 0                 │ 주건축물             │         0.000 │      2508.120 │         0.000 │    107933.280 │               97711.670 │         0.000 │ 14000        │ 업무시설        │ 업무시설, 근린생활시설 │       227.000 │         54 │          2 │              0 │                0.000 │       107933.230 │ NULL    │ NULL    │ 19891103    │ 20250211  │         148784.000 │          88331.320 │          59.370 │      973087.390 │                   531729.320 │         357.380 │ 05000             │ 문화및집회시설       │ 문화및집회시설(업무시설,전시시설,판매시설) │                  0 │                  0 │                 9 │                   0 │                     0.000 │
└────────────────────┴─────────────────────────┴──────────────────────────────┴──────────────────────────────────┴──────────┴─────────┴─────────────┴─────────────┴───────────────────┴──────────────────────┴───────────────┴───────────────┴───────────────┴───────────────┴─────────────────────────┴───────────────┴──────────────┴─────────────────┴────────────────────────┴───────────────┴────────────┴────────────┴────────────────┴──────────────────────┴──────────────────┴─────────┴─────────┴─────────────┴───────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴──────────────────────┴────────────────────────────────────────────┴────────────────────┴────────────────────┴───────────────────┴─────────────────────┴───────────────────────────┘

In [21]:
# 0 as null

query = """
SELECT
  "관리_건축물대장_PK",
  "관리_상위_건축물대장_PK",
  "관리_상위_건축물대장_PK_null" AS 단독,
  "대지_위치",
  "시군구_코드",
  "법정동_코드",
  "주_용도_코드",
  "주_용도_코드_명",
  "기타_용도",
  CAST(NULLIF("대지_면적(㎡)", 0) AS DOUBLE) AS "대지_면적(㎡)",
  CAST(NULLIF("건축_면적(㎡)", 0) AS DOUBLE) AS "건축_면적(㎡)",
  CAST(NULLIF("건폐_율(%)", 0) AS DOUBLE) AS "건폐_율(%)",
  CAST(NULLIF("연면적(㎡)", 0) AS DOUBLE) AS "연면적(㎡)",
  CAST(NULLIF("용적_률_산정_연면적(㎡)", 0) AS DOUBLE) AS "용적_률_산정_연면적(㎡)",
  CAST(NULLIF("용적_률(%)", 0) AS DOUBLE) AS "용적_률(%)",
  CAST(NULLIF("높이(m)", 0) AS DOUBLE) AS "높이(m)",
  "지상_층_수",
  "지하_층_수",
  "사용승인_일",
  CAST(NULLIF("총괄_대지_면적(㎡)", 0) AS DOUBLE) AS "총괄_대지_면적(㎡)",
  CAST(NULLIF("총괄_건축_면적(㎡)", 0) AS DOUBLE) AS "총괄_건축_면적(㎡)",
  CAST(NULLIF("총괄_건폐_율(%)", 0) AS DOUBLE) AS "총괄_건폐_율(%)",
  CAST(NULLIF("총괄_연면적(㎡)", 0) AS DOUBLE) AS "총괄_연면적(㎡)",
  CAST(NULLIF("총괄_용적_률_산정_연면적(㎡)", 0) AS DOUBLE) AS "총괄_용적_률_산정_연면적(㎡)",
  CAST(NULLIF("총괄_용적_률(%)", 0) AS DOUBLE) AS "총괄_용적_률(%)",
  NULLIF("총괄_주_건축물_수", 0) AS "총괄_주_건축물_수",
FROM
  주건축물
"""
rel = con.sql(query)
rel.limit(20).show()
rel.to_parquet("../data/processed/주건축물_표제부_기본개요_총괄표제부.parquet")

┌────────────────────┬─────────────────────────┬─────────┬─────────────────────────────────────┬─────────────┬─────────────┬──────────────┬───────────────────┬────────────────────────┬───────────────┬───────────────┬────────────┬────────────┬─────────────────────────┬────────────┬─────────┬────────────┬────────────┬─────────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │  단독   │              대지_위치              │ 시군구_코드 │ 법정동_코드 │ 주_용도_코드 │  주_용도_코드_명  │       기타_용도        │ 대지_면적(㎡) │ 건축_면적(㎡) │ 건폐_율(%) │ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 용적_률(%) │ 높이(m) │ 지상_층_수 │ 지하_층_수 │ 사용승인_일 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_건축물_수 │
│      varchar       │         varchar         │ boolean │               varchar               │   varchar   │   varchar   │   varchar    │      varchar      │        varchar         │    double     │    double     │   double   │   double   │         double          │   double   │ double  │   int32    │   int32    │   varchar   │       double       │       double       │     double      │     double      │            double            │     double      │       int32       │
├────────────────────┼─────────────────────────┼─────────┼─────────────────────────────────────┼─────────────┼─────────────┼──────────────┼───────────────────┼────────────────────────┼───────────────┼───────────────┼────────────┼────────────┼─────────────────────────┼────────────┼─────────┼────────────┼────────────┼─────────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┤
│ 1024122357         │ 10241394                │ false   │ 서울특별시 강남구 삼성동 159번지    │ 11680       │ 10500       │ 14000        │ 업무시설          │ 업무시설, 근린생활시설 │          NULL │       2508.12 │       NULL │  107933.28 │                97711.67 │       NULL │   227.0 │         54 │          2 │ 19891103    │           148784.0 │           88331.32 │           59.37 │       973087.39 │                    531729.32 │          357.38 │                 9 │
│ 1024123581         │ 10241100252352          │ false   │ 서울특별시 강남구 논현동 140-25번지 │ 11680       │ 10800       │ 01000        │ 단독주택          │ 주거시설               │          NULL │        141.48 │       NULL │     544.91 │                  403.69 │       NULL │    10.5 │          3 │          1 │ 19960115    │              244.2 │             145.86 │           59.73 │          549.11 │                       407.89 │          167.03 │                 2 │
│ 1024124216         │ 10241100276014          │ false   │ 서울특별시 강남구 논현동 121번지    │ 11680       │ 10800       │ 14000        │ 업무시설          │ 업무시설, 판매시설     │          NULL │        782.05 │       NULL │    3099.19 │                 2346.15 │       NULL │    11.7 │          3 │          1 │ 19740920    │             2074.5 │            1023.54 │           49.34 │         4043.24 │                      3159.09 │          152.28 │                 2 │
│ 10241100181447     │ 10241100198307          │ false   │ 서울특별시 강남구 대치동 500번지    │ 11680       │ 10600       │ 07000        │ 판매시설          │ 판매시설               │          NULL │       2040.33 │       NULL │    9482.35 │                 6084.08 │       NULL │    NULL │          3 │          1 │ 19841215    │               NULL │               NULL │            NULL │        72027.55 │                         NULL │            NULL │                 6 │
│ 10241100181572     │ 10241100198307          │ false   │ 서울특별시 강남구 대치동 500번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 주거시설               │          NULL │        849.36 │       NULL │    13194.0 │                 12362.4 │       NULL │    NULL │         15 │          1 │ 19841215    │               NULL │               NULL │            NULL │        72027.55 │                         NULL │            NULL │                 6 │
│ 10241100181760     │ 10241100198307          │ false   │ 서울특별시 강남구 대치동 500번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 주거시설               │          NULL │        791.52 │       NULL │    12130.8 │                 11368.8 │       NULL │    NULL │         15 │          1 │ 19841215    │               NULL │               NULL │            NULL │        72027.55 │                         NULL │            NULL │                 6 │
│ 10241100184210     │ 10241100183823          │ false   │ 서울특별시 강남구 대치동 888번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 공동주택(아파트)       │          NULL │        582.22 │       NULL │   18033.06 │                12214.98 │       NULL │    66.6 │         24 │          2 │ 20080603    │            36229.1 │            5218.28 │            14.4 │       147441.71 │                     99609.07 │          274.94 │                11 │
│ 10241100184473     │ 10241100183823          │ false   │ 서울특별시 강남구 대치동 888번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 공동주택(아파트)       │          NULL │        509.59 │       NULL │   15793.89 │                10747.35 │       NULL │    67.9 │         25 │          2 │ 20080603    │            36229.1 │            5218.28 │            14.4 │       147441.71 │                     99609.07 │          274.94 │                11 │
│ 10241100184762     │ 10241100183823          │ false   │ 서울특별시 강남구 대치동 888번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 공동주택(아파트)       │          NULL │        192.29 │       NULL │    4135.73 │                 2827.49 │       NULL │    48.3 │         18 │          2 │ 20080603    │            36229.1 │            5218.28 │            14.4 │       147441.71 │                     99609.07 │          274.94 │                11 │
│ 10241100184794     │ 10241100183823          │ false   │ 서울특별시 강남구 대치동 888번지    │ 11680       │ 10600       │ 02000        │ 공동주택          │ 공동주택(아파트)       │          NULL │         542.8 │       NULL │   15004.78 │                10216.36 │       NULL │    65.1 │         24 │          2 │ 20080603    │            36229.1 │            5218.28 │            14.4 │       147441.71 │                     99609.07 │          274.94 │                11 │
│ 10241100188020     │ 10241100187712          │ false   │ 서울특별시 강남구 대치동 66번지     │ 11680       │ 10600       │ 03000        │ 제1종근린생활시설 │ 근린생활시설           │          NULL │        839.67 │       NULL │    5805.85 │                 2513.01 │       NULL │    NULL │          3 │          2 │ 19830307    │               NULL │            6443.89 │            NULL │        92303.75 │                     80273.35 │            NULL │                 6 │
│ 10241100188101     │ 10241100187712          │ false   │ 서울특별시 강남구 대치동 66번지     │ 11680       │ 10600       │ 02000        │ 공동주택          │ 주거시설               │          NULL │       1457.98 │       NULL │   21317.51 │                19681.78 │       NULL │    NULL │         15 │          1 │ 19830307    │               NULL │            6443.89 │            NULL │        92303.75 │                     80273.35 │            NULL │                 6 │
│ 10241100188227     │ 10241100187712          │ false   │ 서울특별시 강남구 대치동 66번지     │ 11680       │ 10600       │ 02000        │ 공동주택          │ 주거시설               │          NULL │       1129.72 │       NULL │   18066.52 │                 16945.8 │       NULL │    NULL │         15 │          1 │ 19830307    │               NULL │            6443.89 │            NULL │        92303.75 │                     80273.35 │            NULL │                 6 │
│ 10241100188432     │ 10241100188433          │ false   │ 서울특별시 강남구 역삼동 727-1번지  │ 11680       │ 10100       │ 04000        │ 제2종근린생활시설 │ 근린생활시설           │          NULL │         245.9 │       NULL │     585.66 │                  557.59 │       NULL │     7.9 │          2 │          1 │ 19780810    │              874.5 │             390.99 │           44.71 │           736.8 │                       708.73 │           81.04 │                 2 │
│ 10241100188450     │ 10241100188447          │ false   │ 서울특별시 강남구 대치동 510번지    │ 11680       │ 10600       │ 10000        │ 교육연구시설      │ 교육연구시설           │          NULL │         495.0 │       NULL │     1980.0 │                  1980.0 │       NULL │    NULL │          4 │          0 │ 20081027    │            14335.3 │            2715.07 │           18.94 │          8648.9 │                       8754.9 │           60.33 │                 4 │
│ 10241100188508     │ 10241100188507          │ false   │ 서울특별시 강남구 대치동 924-10번지 │ 11680       │ 10600       │ 10000        │ 교육연구시설      │ 교육연구시설           │          NULL │         900.0 │       NULL │     3600.0 │                  3600.0 │       NULL │    NULL │          4 │          0 │ 20081027    │            16493.1 │            1962.66 │            11.9 │         7942.26 │                      7627.26 │           46.25 │                 2 │
│ 10241100189208     │ 10241100189207          │ false   │ 서울특별시 강남구 삼성동 16-2번지   │ 11680       │ 10500       │ 02000        │ 공동주택          │ 아파트                 │          NULL │       635.132 │       NULL │  10289.312 │               10289.312 │       NULL │   57.05 │         21 │          0 │ 20081210    │            42862.4 │           8546.604 │           19.94 │      180448.969 │                   118622.655 │         276.752 │                18 │
│ 10241100189622     │ 10241100189207          │ false   │ 서울특별시 강남구 삼성동 16-2번지   │ 11680       │ 10500       │ 02000        │ 공동주택          │ 아파트                 │          NULL │       525.842 │       NULL │   9621.744 │                9621.744 │       NULL │   59.85 │         22 │          0 │ 20081210    │            42862.4 │           8546.604 │           19.94 │      180448.969 │                   118622.655 │         276.752 │                18 │
│ 10241100190097     │ 10241100195447          │ false   │ 서울특별시 강남구 삼성동 50번지     │ 11680       │ 10500       │ 02000        │ 공동주택          │ 아파트                 │          NULL │        547.65 │       NULL │   8324.274 │                8324.274 │       NULL │  53.208 │         19 │          0 │ 20081210    │            34315.4 │           6654.639 │           19.39 │      147738.618 │                    93703.082 │          273.06 │                13 │
│ 10241100190250     │ 10241100189207          │ false   │ 서울특별시 강남구 삼성동 16-2번지   │ 11680       │ 10500       │ 02000        │ 공동주택          │ 아파트                 │          NULL │       636.322 │       NULL │  10355.664 │               10355.664 │       NULL │   59.72 │         21 │          0 │ 20081210    │            42862.4 │           8546.604 │           19.94 │      180448.969 │                   118622.655 │         276.752 │                18 │
├────────────────────┴─────────────────────────┴─────────┴─────────────────────────────────────┴─────────────┴─────────────┴──────────────┴───────────────────┴────────────────────────┴───────────────┴───────────────┴────────────┴────────────┴─────────────────────────┴────────────┴─────────┴────────────┴────────────┴─────────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┤
│ 20 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                         26 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

---

In [22]:
rel_orig = con.from_parquet(
    "../data/processed/주건축물_표제부_기본개요_총괄표제부.parquet"
)

con.sql("DESCRIBE rel_orig").show(max_rows=100)

┌──────────────────────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐
│         column_name          │ column_type │  null   │   key   │ default │  extra  │
│           varchar            │   varchar   │ varchar │ varchar │ varchar │ varchar │
├──────────────────────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤
│ 관리_건축물대장_PK           │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 관리_상위_건축물대장_PK      │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 단독                         │ BOOLEAN     │ YES     │ NULL    │ NULL    │ NULL    │
│ 대지_위치                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 시군구_코드                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 법정동_코드                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 주_용도_코드                 │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 주_용도_코드_명              │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 기타_용도                    │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 대지_면적(㎡)                │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 건축_면적(㎡)                │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 건폐_율(%)                   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 연면적(㎡)                   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 용적_률_산정_연면적(㎡)      │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 용적_률(%)                   │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 높이(m)                      │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 지상_층_수                   │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ 지하_층_수                   │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
│ 사용승인_일                  │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_대지_면적(㎡)           │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_건축_면적(㎡)           │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_건폐_율(%)              │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_연면적(㎡)              │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_용적_률_산정_연면적(㎡) │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_용적_률(%)              │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │
│ 총괄_주_건축물_수            │ INTEGER     │ YES     │ NULL    │ NULL    │ NULL    │
├──────────────────────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┤
│ 26 rows                                                                  6 columns │
└────────────────────────────────────────────────────────────────────────────────────┘

## 기존 규칙

### 14. (대지면적) 일반건축물대장 및 표제부 내 대지면적의 값이 건축면적보다 작은 경우

In [23]:
query = """
SELECT
  "대지_면적(㎡)",
  "총괄_대지_면적(㎡)",
  "건축_면적(㎡)",
  COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)") < "건축_면적(㎡)" - 1 AS 기존14,
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬────────────────────┬───────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 기존14  │
│    double     │       double       │    double     │ boolean │
├───────────────┼────────────────────┼───────────────┼─────────┤
│          NULL │               NULL │          NULL │ NULL    │
│         513.0 │               NULL │        227.82 │ false   │
│          NULL │               NULL │          NULL │ NULL    │
│          NULL │               NULL │          NULL │ NULL    │
│          NULL │               NULL │          NULL │ NULL    │
└───────────────┴────────────────────┴───────────────┴─────────┘

In [24]:
query = """
SELECT *
FROM
  rel
WHERE
  기존14 = true
"""
con.sql(query).show()

┌───────────────┬────────────────────┬───────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 기존14  │
│    double     │       double       │    double     │ boolean │
├───────────────┼────────────────────┼───────────────┼─────────┤
│          52.9 │               NULL │         85.16 │ true    │
│         297.2 │               NULL │         347.0 │ true    │
│         218.2 │               NULL │         285.5 │ true    │
│          26.8 │               NULL │         42.94 │ true    │
│         476.0 │               NULL │        477.65 │ true    │
│          76.1 │               NULL │         82.45 │ true    │
│          72.7 │               NULL │         76.79 │ true    │
│          85.0 │               NULL │         91.07 │ true    │
│        3435.4 │               NULL │       4418.74 │ true    │
│          86.0 │               NULL │         89.12 │ true    │
│            ·  │                 ·  │            ·  │  ·      │
│            ·  │                 ·  │            ·  │  ·      │
│            ·  │                 ·  │            ·  │  ·      │
│         1.025 │               NULL │          92.8 │ true    │
│         184.0 │               NULL │        299.64 │ true    │
│         209.6 │               NULL │        263.88 │ true    │
│         188.0 │               NULL │        236.68 │ true    │
│          18.0 │               NULL │         66.11 │ true    │
│          52.0 │               NULL │         56.19 │ true    │
│           7.0 │               NULL │         26.11 │ true    │
│          10.0 │               NULL │         49.58 │ true    │
│         323.7 │               NULL │        788.98 │ true    │
│          43.0 │               NULL │         50.24 │ true    │
├───────────────┴────────────────────┴───────────────┴─────────┤
│ 9773 rows (20 shown)                               4 columns │
└──────────────────────────────────────────────────────────────┘

In [25]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 기존14, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 기존14  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 5190727 │
│ true    │    9773 │
│ NULL    │ 2164467 │
└─────────┴─────────┘

### 16. (건축면적) 일반건축물대장 및 표제부의 연면적이 표제부의 건축면적보다 작은 경우

In [26]:
query = """
SELECT
  "건축_면적(㎡)",
  "연면적(㎡)",
  "연면적(㎡)" < "건축_면적(㎡)" - 1 AS 기존16,
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬────────────┬─────────┐
│ 건축_면적(㎡) │ 연면적(㎡) │ 기존16  │
│    double     │   double   │ boolean │
├───────────────┼────────────┼─────────┤
│          NULL │      29.75 │ NULL    │
│        227.82 │    1659.98 │ false   │
│          NULL │     169.38 │ NULL    │
│          NULL │      44.33 │ NULL    │
│          NULL │      36.26 │ NULL    │
└───────────────┴────────────┴─────────┘

In [27]:
query = """
SELECT *
FROM
  rel
WHERE
  기존16 = true
"""
con.sql(query).show()

┌───────────────┬────────────┬─────────┐
│ 건축_면적(㎡) │ 연면적(㎡) │ 기존16  │
│    double     │   double   │ boolean │
├───────────────┼────────────┼─────────┤
│         92.33 │      87.87 │ true    │
│       4832.03 │     450.04 │ true    │
│       4832.03 │    1637.28 │ true    │
│       2130.67 │    1299.78 │ true    │
│       2130.67 │     637.08 │ true    │
│       2130.67 │     1280.0 │ true    │
│       4458.44 │    2580.32 │ true    │
│       4458.44 │     1460.8 │ true    │
│       7470.43 │     3353.2 │ true    │
│       7470.43 │     2240.0 │ true    │
│           ·   │        ·   │  ·      │
│           ·   │        ·   │  ·      │
│           ·   │        ·   │  ·      │
│        230.65 │     183.92 │ true    │
│      1233.298 │    398.409 │ true    │
│      1243.765 │     382.01 │ true    │
│      3821.645 │   2523.922 │ true    │
│        350.04 │     348.89 │ true    │
│       226.628 │     223.48 │ true    │
│         392.7 │      376.2 │ true    │
│         49.15 │      41.05 │ true    │
│        128.98 │     124.83 │ true    │
│         31.88 │       22.4 │ true    │
├───────────────┴────────────┴─────────┤
│    ? rows (>9999 rows, 20 shown)     │
└──────────────────────────────────────┘

In [28]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 기존16, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 기존16  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 6647554 │
│ true    │  373505 │
│ NULL    │  343908 │
└─────────┴─────────┘

### 19. (건폐율) 일반건축물대장 및 표제부 건폐율 계산의 정확성

→ 소수점 이하 처리에 대한 명확한 법규 처리 없어 반올림 자리수가 불분명함(소숫점 이하 절사처리)

In [29]:
query = """
SELECT
  "대지_면적(㎡)",
  "건축_면적(㎡)",
  "건폐_율(%)",
  "건축_면적(㎡)" / "대지_면적(㎡)" * 100 AS 건폐율_재계산,
  ("건폐_율(%)" - 건폐율_재계산) AS 건폐율_차이,
  ABS(건폐율_차이) > 0.1 AS 기존19
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬───────────────┬────────────┬────────────────────┬───────────────────────┬─────────┐
│ 대지_면적(㎡) │ 건축_면적(㎡) │ 건폐_율(%) │   건폐율_재계산    │      건폐율_차이      │ 기존19  │
│    double     │    double     │   double   │       double       │        double         │ boolean │
├───────────────┼───────────────┼────────────┼────────────────────┼───────────────────────┼─────────┤
│          NULL │          NULL │       NULL │               NULL │                  NULL │ NULL    │
│         513.0 │        227.82 │       44.4 │ 44.409356725146196 │ -0.009356725146197675 │ false   │
│          NULL │          NULL │       NULL │               NULL │                  NULL │ NULL    │
│          NULL │          NULL │       NULL │               NULL │                  NULL │ NULL    │
│          NULL │          NULL │       NULL │               NULL │                  NULL │ NULL    │
└───────────────┴───────────────┴────────────┴────────────────────┴───────────────────────┴─────────┘

In [30]:
query = """
SELECT *
FROM
  rel
WHERE
  건폐율_차이 is not null
"""
con.sql(query).limit(20).show()

┌───────────────┬───────────────┬────────────┬────────────────────┬─────────────────────────┬─────────┐
│ 대지_면적(㎡) │ 건축_면적(㎡) │ 건폐_율(%) │   건폐율_재계산    │       건폐율_차이       │ 기존19  │
│    double     │    double     │   double   │       double       │         double          │ boolean │
├───────────────┼───────────────┼────────────┼────────────────────┼─────────────────────────┼─────────┤
│         513.0 │        227.82 │       44.4 │ 44.409356725146196 │   -0.009356725146197675 │ false   │
│        614.52 │        338.25 │      55.04 │  55.04296035930483 │  -0.0029603593048292964 │ false   │
│         61.88 │         45.37 │      73.29 │  73.31932773109243 │   -0.029327731092422482 │ false   │
│         152.4 │         87.72 │      57.56 │  57.55905511811024 │     0.00094488188976527 │ false   │
│         546.0 │        163.26 │     29.901 │ 29.901098901098898 │   -9.89010988980965e-05 │ false   │
│       12158.4 │        767.57 │      6.313 │  6.313083958415581 │  -8.395841558161976e-05 │ false   │
│        1266.0 │          56.7 │       4.48 │  4.478672985781991 │   0.0013270142180097366 │ false   │
│         540.2 │        288.97 │      53.49 │ 53.493150684931514 │    -0.00315068493151216 │ false   │
│        3096.4 │         60.21 │      39.21 │  1.944516212375662 │       37.26548378762434 │ true    │
│       53815.0 │        528.11 │       0.98 │ 0.9813434915915638 │  -0.0013434915915637724 │ false   │
│         498.7 │        150.67 │      30.21 │ 30.212552636855822 │  -0.0025526368558210777 │ false   │
│         498.7 │        148.36 │      29.75 │  29.74934830559455 │   0.0006516944054517637 │ false   │
│        2412.0 │       1399.83 │      58.04 │  58.03606965174129 │   0.0039303482587058625 │ false   │
│         242.4 │          9.75 │       4.02 │  4.022277227722772 │  -0.0022772277227725013 │ false   │
│         307.0 │        153.09 │      49.87 │  49.86644951140065 │   0.0035504885993447033 │ false   │
│        2314.9 │        630.89 │     27.253 │ 27.253445073221304 │  -0.0004450732213037156 │ false   │
│        1692.4 │        565.72 │      33.43 │  33.42708579532025 │   0.0029142046797474563 │ false   │
│          56.8 │         33.42 │      58.83 │  58.83802816901409 │   -0.008028169014089315 │ false   │
│          92.6 │         46.67 │      50.39 │  50.39956803455724 │   -0.009568034557240424 │ false   │
│       15711.8 │        889.19 │      5.659 │      5.65937702873 │ -0.00037702873000000636 │ false   │
├───────────────┴───────────────┴────────────┴────────────────────┴─────────────────────────┴─────────┤
│ 20 rows                                                                                   6 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [31]:
query = """
SELECT *
FROM
  rel
WHERE
  기존19 = true
"""
con.sql(query).limit(20).show()

┌───────────────┬───────────────┬────────────┬────────────────────┬──────────────────────┬─────────┐
│ 대지_면적(㎡) │ 건축_면적(㎡) │ 건폐_율(%) │   건폐율_재계산    │     건폐율_차이      │ 기존19  │
│    double     │    double     │   double   │       double       │        double        │ boolean │
├───────────────┼───────────────┼────────────┼────────────────────┼──────────────────────┼─────────┤
│        3096.4 │         60.21 │      39.21 │  1.944516212375662 │    37.26548378762434 │ true    │
│       78580.0 │       2175.43 │      18.97 │  2.768427080682107 │    16.20157291931789 │ true    │
│       14549.8 │        804.74 │      24.48 │ 5.5309351331289776 │   18.949064866871023 │ true    │
│       14549.8 │        351.89 │      24.48 │ 2.4185212167864854 │   22.061478783213516 │ true    │
│        4125.0 │        409.66 │      29.97 │  9.931151515151516 │   20.038848484848483 │ true    │
│        4125.0 │        410.53 │      29.97 │  9.952242424242423 │   20.017757575757578 │ true    │
│          83.6 │          76.1 │      48.74 │  91.02870813397129 │   -42.28870813397129 │ true    │
│          91.7 │          59.5 │      59.97 │   64.8854961832061 │   -4.915496183206102 │ true    │
│         308.0 │         65.95 │      21.55 │ 21.412337662337663 │  0.13766233766233782 │ true    │
│         476.0 │         240.4 │      27.91 │  50.50420168067227 │  -22.594201680672267 │ true    │
│       1993.92 │       1002.87 │      50.02 │  50.29640105922003 │  -0.2764010592200279 │ true    │
│        271.33 │        271.33 │      57.42 │              100.0 │               -42.58 │ true    │
│        1835.4 │        893.17 │      48.53 │ 48.663506592568375 │  -0.1335065925683736 │ true    │
│         152.4 │         60.86 │       47.0 │  39.93438320209974 │    7.065616797900262 │ true    │
│         133.5 │         78.16 │      58.74 │ 58.546816479400746 │   0.1931835205992556 │ true    │
│         238.0 │         85.99 │       36.0 │  36.13025210084033 │ -0.13025210084033034 │ true    │
│        116.95 │         87.05 │      74.74 │  74.43351859769132 │   0.3064814023086768 │ true    │
│        815.89 │        439.92 │       54.9 │ 53.919033203005306 │   0.9809667969946929 │ true    │
│         661.0 │        192.49 │      29.94 │ 29.121028744326775 │    0.818971255673226 │ true    │
│          76.4 │         61.08 │    79095.0 │  79.94764397905757 │    79015.05235602094 │ true    │
├───────────────┴───────────────┴────────────┴────────────────────┴──────────────────────┴─────────┤
│ 20 rows                                                                                6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘

In [32]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 기존19, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 기존19  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 3942599 │
│ true    │   85541 │
│ NULL    │ 3336827 │
└─────────┴─────────┘

### 20. (용적률) 일반건축물대장 및 표제부 용적율 계산의 정확성

In [33]:
query = """
SELECT
  "대지_면적(㎡)",
  "용적_률_산정_연면적(㎡)",
  "용적_률(%)",
  "용적_률_산정_연면적(㎡)" / "대지_면적(㎡)" * 100 AS 용적률_재계산,
  ("용적_률(%)" - 용적률_재계산) AS 용적률_차이,
  ABS(용적률_차이) > 0.1 AS 기존20
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬─────────────────────────┬────────────┬────────────────────┬────────────────────┬─────────┐
│ 대지_면적(㎡) │ 용적_률_산정_연면적(㎡) │ 용적_률(%) │   용적률_재계산    │    용적률_차이     │ 기존20  │
│    double     │         double          │   double   │       double       │       double       │ boolean │
├───────────────┼─────────────────────────┼────────────┼────────────────────┼────────────────────┼─────────┤
│          NULL │                    NULL │       NULL │               NULL │               NULL │ NULL    │
│         513.0 │                  659.85 │     281.04 │ 128.62573099415204 │ 152.41426900584798 │ true    │
│          NULL │                    NULL │       NULL │               NULL │               NULL │ NULL    │
│          NULL │                    NULL │       NULL │               NULL │               NULL │ NULL    │
│          NULL │                    NULL │       NULL │               NULL │               NULL │ NULL    │
└───────────────┴─────────────────────────┴────────────┴────────────────────┴────────────────────┴─────────┘

In [34]:
query = """
SELECT *
FROM
  rel
WHERE
  용적률_차이 is not null
"""
con.sql(query).limit(20).show()

┌───────────────┬─────────────────────────┬────────────┬────────────────────┬────────────────────────┬─────────┐
│ 대지_면적(㎡) │ 용적_률_산정_연면적(㎡) │ 용적_률(%) │   용적률_재계산    │      용적률_차이       │ 기존20  │
│    double     │         double          │   double   │       double       │         double         │ boolean │
├───────────────┼─────────────────────────┼────────────┼────────────────────┼────────────────────────┼─────────┤
│         513.0 │                  659.85 │     281.04 │ 128.62573099415204 │     152.41426900584798 │ true    │
│        614.52 │                 1687.41 │     274.59 │ 274.58992384299944 │  7.615700053520413e-05 │ false   │
│         546.0 │                   265.6 │      48.64 │  48.64468864468865 │  -0.004688644688648935 │ false   │
│       12158.4 │                 6026.26 │     49.565 │ 49.564580865903416 │  0.0004191340965817858 │ false   │
│        1266.0 │                    56.7 │       4.48 │  4.478672985781991 │  0.0013270142180097366 │ false   │
│         540.2 │                  504.11 │       93.3 │  93.31914105886709 │  -0.019141058867091942 │ false   │
│       53815.0 │                 1562.15 │        2.9 │ 2.9028152002229866 │  -0.002815200222986647 │ false   │
│        2412.0 │                 3160.24 │     131.02 │ 131.02155887230512 │  -0.001558872305110981 │ false   │
│         242.4 │                    9.75 │       4.02 │  4.022277227722772 │ -0.0022772277227725013 │ false   │
│         307.0 │                  153.09 │      49.87 │  49.86644951140065 │  0.0035504885993447033 │ false   │
│        2314.9 │                 2454.55 │    106.033 │ 106.03265799818567 │ 0.00034200181433163834 │ false   │
│        1692.4 │                 1640.22 │      96.92 │  96.91680453793428 │   0.003195462065718857 │ false   │
│          92.6 │                   46.67 │      50.39 │  50.39956803455724 │  -0.009568034557240424 │ false   │
│       15711.8 │                12779.83 │     81.339 │  81.33905726905893 │ -5.726905892800005e-05 │ false   │
│       78580.0 │                  1823.9 │       2.32 │  2.321074064647493 │ -0.0010740646474931559 │ false   │
│       78580.0 │                10325.77 │      69.57 │ 13.140455586663274 │      56.42954441333672 │ true    │
│        204.31 │                  559.84 │    274.015 │ 274.01497724046794 │  2.275953204389225e-05 │ false   │
│       14549.8 │                13107.33 │     335.56 │   90.0859805633067 │      245.4740194366933 │ true    │
│       14549.8 │                  891.79 │     335.56 │  6.129225143988234 │      329.4307748560118 │ true    │
│         741.2 │                  708.68 │      95.61 │  95.61252023745277 │  -0.002520237452770857 │ false   │
├───────────────┴─────────────────────────┴────────────┴────────────────────┴────────────────────────┴─────────┤
│ 20 rows                                                                                            6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [35]:
query = """
SELECT *
FROM
  rel
WHERE
  기존20 = true
"""
con.sql(query).limit(20).show()

┌───────────────┬─────────────────────────┬────────────┬────────────────────┬──────────────────────┬─────────┐
│ 대지_면적(㎡) │ 용적_률_산정_연면적(㎡) │ 용적_률(%) │   용적률_재계산    │     용적률_차이      │ 기존20  │
│    double     │         double          │   double   │       double       │        double        │ boolean │
├───────────────┼─────────────────────────┼────────────┼────────────────────┼──────────────────────┼─────────┤
│         513.0 │                  659.85 │     281.04 │ 128.62573099415204 │   152.41426900584798 │ true    │
│       78580.0 │                10325.77 │      69.57 │ 13.140455586663274 │    56.42954441333672 │ true    │
│       14549.8 │                13107.33 │     335.56 │   90.0859805633067 │    245.4740194366933 │ true    │
│       14549.8 │                  891.79 │     335.56 │  6.129225143988234 │    329.4307748560118 │ true    │
│         368.3 │                  154.52 │      59.78 │ 41.954928047787135 │   17.825071952212866 │ true    │
│          40.8 │                    67.0 │       67.0 │  164.2156862745098 │    -97.2156862745098 │ true    │
│         308.0 │                  112.79 │      36.86 │  36.62012987012987 │   0.2398701298701269 │ true    │
│         132.0 │                  122.44 │      94.27 │  92.75757575757576 │   1.5124242424242311 │ true    │
│         88.42 │                 2549.17 │     185.05 │ 2883.0242026690794 │   -2697.974202669079 │ true    │
│        435.65 │                   60.85 │     202.29 │ 13.967634569034775 │   188.32236543096522 │ true    │
│          99.0 │                    29.1 │       90.0 │ 29.393939393939394 │    60.60606060606061 │ true    │
│         146.4 │                 1012.04 │     108.79 │  691.2841530054644 │   -582.4941530054645 │ true    │
│         152.4 │                   164.3 │     108.14 │ 107.80839895013123 │  0.33160104986876604 │ true    │
│          74.7 │                   99.78 │     104.42 │ 133.57429718875503 │  -29.154297188755024 │ true    │
│        3281.1 │                 5152.54 │     168.66 │ 157.03696930907319 │    11.62303069092681 │ true    │
│        1472.3 │                 2085.38 │      141.5 │ 141.64096991102357 │ -0.14096991102357492 │ true    │
│          68.8 │                  207.03 │      72.81 │ 300.91569767441865 │  -228.10569767441865 │ true    │
│        512.12 │                    52.9 │      78.44 │ 10.329610247598218 │    68.11038975240177 │ true    │
│         105.8 │                   50.99 │      50.99 │ 48.194706994328925 │    2.795293005671077 │ true    │
│         126.4 │                  377.62 │     298.63 │             298.75 │ -0.12000000000000455 │ true    │
├───────────────┴─────────────────────────┴────────────┴────────────────────┴──────────────────────┴─────────┤
│ 20 rows                                                                                          6 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [36]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 기존20, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 기존20  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 3886770 │
│ true    │   82136 │
│ NULL    │ 3396061 │
└─────────┴─────────┘

## 추가 규칙

### 01. 연면적이 용적률 산정 연면적보다 작음

In [37]:
query = """
SELECT
  "연면적(㎡)",
  "용적_률_산정_연면적(㎡)",
  "연면적(㎡)" < "용적_률_산정_연면적(㎡)" - 1 AS 신규01
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌────────────┬─────────────────────────┬─────────┐
│ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 신규01  │
│   double   │         double          │ boolean │
├────────────┼─────────────────────────┼─────────┤
│      29.75 │                    NULL │ NULL    │
│    1659.98 │                  659.85 │ false   │
│     169.38 │                    NULL │ NULL    │
│      44.33 │                    NULL │ NULL    │
│      36.26 │                    NULL │ NULL    │
└────────────┴─────────────────────────┴─────────┘

In [38]:
query = """
SELECT *
FROM
  rel
WHERE
  신규01 is not null
"""
con.sql(query).limit(20).show()

┌────────────┬─────────────────────────┬─────────┐
│ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 신규01  │
│   double   │         double          │ boolean │
├────────────┼─────────────────────────┼─────────┤
│    1659.98 │                  659.85 │ false   │
│     314.84 │                  236.47 │ false   │
│     693.41 │                  531.52 │ false   │
│      267.8 │                  184.58 │ false   │
│     232.85 │                  198.81 │ false   │
│     126.96 │                  126.96 │ false   │
│     380.18 │                   201.4 │ false   │
│    1147.64 │                 1147.64 │ false   │
│    2025.42 │                 1687.41 │ false   │
│     120.18 │                  120.18 │ false   │
│      114.9 │                   57.45 │ false   │
│     492.72 │                  492.72 │ false   │
│    2399.01 │                 2298.66 │ false   │
│    2009.93 │                 2009.93 │ false   │
│   12132.07 │                11797.99 │ false   │
│      853.7 │                  682.96 │ false   │
│     290.89 │                   265.6 │ false   │
│    3574.76 │                 1354.94 │ false   │
│    4152.95 │                 4152.95 │ false   │
│    6602.26 │                 6026.26 │ false   │
├────────────┴─────────────────────────┴─────────┤
│ 20 rows                              3 columns │
└────────────────────────────────────────────────┘

In [39]:
query = """
SELECT *
FROM
  rel
WHERE
  신규01 = true
"""
con.sql(query).limit(20).show()

┌────────────┬─────────────────────────┬─────────┐
│ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 신규01  │
│   double   │         double          │ boolean │
├────────────┼─────────────────────────┼─────────┤
│      87.87 │                   92.33 │ true    │
│    9803.01 │                10609.94 │ true    │
│     225.02 │                 2549.17 │ true    │
│     245.73 │                 1012.04 │ true    │
│      84.88 │                  207.03 │ true    │
│     149.54 │                 4224.22 │ true    │
│    1747.75 │                 1888.74 │ true    │
│      81.57 │                 2549.17 │ true    │
│     152.95 │                  179.84 │ true    │
│     347.88 │                 1012.04 │ true    │
│      71.66 │                  179.84 │ true    │
│      269.8 │                 4224.22 │ true    │
│      70.31 │                  179.84 │ true    │
│     284.82 │                  340.86 │ true    │
│     731.12 │                  733.82 │ true    │
│       88.0 │                 2549.17 │ true    │
│      76.34 │                  179.84 │ true    │
│     289.38 │                 2549.17 │ true    │
│     434.48 │                  449.28 │ true    │
│    1101.69 │                 8026.89 │ true    │
├────────────┴─────────────────────────┴─────────┤
│ 20 rows                              3 columns │
└────────────────────────────────────────────────┘

In [40]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 신규01, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 신규01  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 6999231 │
│ true    │   19295 │
│ NULL    │  346441 │
└─────────┴─────────┘

### 02. 연면적이 (건축면적×지상층수)+(대지면적×지하층수)보다 큼

In [41]:
query = """
SELECT
  "대지_면적(㎡)",
  "총괄_대지_면적(㎡)",
  "건축_면적(㎡)",
  "연면적(㎡)",
  지상_층_수,
  지하_층_수,
  ("건축_면적(㎡)" * 지상_층_수) + (COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)") * 지하_층_수) AS 연면적_상한,
  "연면적(㎡)" > 연면적_상한 + 1 AS 신규02
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬────────────────────┬───────────────┬────────────┬────────────┬────────────┬─────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 연면적(㎡) │ 지상_층_수 │ 지하_층_수 │ 연면적_상한 │ 신규02  │
│    double     │       double       │    double     │   double   │   int32    │   int32    │   double    │ boolean │
├───────────────┼────────────────────┼───────────────┼────────────┼────────────┼────────────┼─────────────┼─────────┤
│          NULL │               NULL │          NULL │      29.75 │          1 │          0 │        NULL │ NULL    │
│         513.0 │               NULL │        227.82 │    1659.98 │          7 │          1 │     2107.74 │ false   │
│          NULL │               NULL │          NULL │     169.38 │          2 │          0 │        NULL │ NULL    │
│          NULL │               NULL │          NULL │      44.33 │          1 │          0 │        NULL │ NULL    │
│          NULL │               NULL │          NULL │      36.26 │          1 │          0 │        NULL │ NULL    │
└───────────────┴────────────────────┴───────────────┴────────────┴────────────┴────────────┴─────────────┴─────────┘

In [42]:
query = """
SELECT *
FROM
  rel
WHERE
  신규02 is not null
"""
con.sql(query).limit(20).show()

┌───────────────┬────────────────────┬───────────────┬────────────┬────────────┬────────────┬────────────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 연면적(㎡) │ 지상_층_수 │ 지하_층_수 │    연면적_상한     │ 신규02  │
│    double     │       double       │    double     │   double   │   int32    │   int32    │       double       │ boolean │
├───────────────┼────────────────────┼───────────────┼────────────┼────────────┼────────────┼────────────────────┼─────────┤
│         513.0 │               NULL │        227.82 │    1659.98 │          7 │          1 │            2107.74 │ false   │
│          NULL │              658.0 │        136.18 │     314.84 │          2 │          1 │             930.36 │ false   │
│          NULL │              793.0 │        141.82 │     693.41 │          4 │          1 │            1360.28 │ false   │
│          NULL │              624.0 │        120.47 │      267.8 │          2 │          1 │             864.94 │ false   │
│          NULL │              624.0 │        126.81 │     232.85 │          2 │          0 │             253.62 │ false   │
│          NULL │             945.92 │         66.12 │     126.96 │          2 │          0 │             132.24 │ false   │
│          NULL │             945.92 │         100.7 │     380.18 │          2 │          1 │            1147.32 │ false   │
│          NULL │              608.0 │        151.96 │    1147.64 │          8 │          0 │            1215.68 │ false   │
│        614.52 │             614.52 │        338.25 │    2025.42 │          5 │          1 │            2305.77 │ false   │
│          NULL │              331.0 │         47.54 │     120.18 │          2 │          0 │              95.08 │ true    │
│         61.88 │               NULL │         45.37 │     159.72 │          3 │          1 │ 197.98999999999998 │ false   │
│        9383.0 │             9383.0 │          90.0 │     472.05 │          3 │          1 │             9653.0 │ false   │
│          NULL │            1395.96 │         57.45 │      114.9 │          1 │          1 │            1453.41 │ false   │
│          NULL │             1937.0 │        208.55 │     492.72 │          3 │          0 │  625.6500000000001 │ false   │
│          NULL │            47840.1 │        804.66 │    2399.01 │          3 │          1 │           50254.08 │ false   │
│          NULL │            47840.1 │        548.74 │    2009.93 │          4 │          0 │            2194.96 │ false   │
│          NULL │              431.7 │        170.74 │      853.7 │          4 │          1 │            1114.66 │ false   │
│         152.4 │              431.7 │         87.72 │     626.85 │          6 │          1 │  678.7199999999999 │ false   │
│         546.0 │              546.0 │        163.26 │     290.89 │          2 │          1 │             872.52 │ false   │
│          NULL │            2444.96 │         632.2 │    3574.76 │          4 │          2 │            7418.72 │ false   │
├───────────────┴────────────────────┴───────────────┴────────────┴────────────┴────────────┴────────────────────┴─────────┤
│ 20 rows                                                                                                        8 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [43]:
query = """
SELECT *
FROM
  rel
WHERE
  신규02 = true
"""
con.sql(query).limit(20).show()

┌───────────────┬────────────────────┬───────────────┬────────────┬────────────┬────────────┬────────────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 연면적(㎡) │ 지상_층_수 │ 지하_층_수 │    연면적_상한     │ 신규02  │
│    double     │       double       │    double     │   double   │   int32    │   int32    │       double       │ boolean │
├───────────────┼────────────────────┼───────────────┼────────────┼────────────┼────────────┼────────────────────┼─────────┤
│          NULL │              331.0 │         47.54 │     120.18 │          2 │          0 │              95.08 │ true    │
│          NULL │            56242.6 │       1102.48 │    4449.59 │          4 │          0 │            4409.92 │ true    │
│        4097.1 │               NULL │         771.6 │    1307.85 │          1 │          0 │              771.6 │ true    │
│          67.4 │               NULL │         48.45 │     124.33 │          2 │          0 │               96.9 │ true    │
│          39.7 │               NULL │          9.84 │      67.28 │          2 │          0 │              19.68 │ true    │
│        1104.1 │               NULL │        173.85 │     187.72 │          1 │          0 │             173.85 │ true    │
│         172.6 │               NULL │        100.07 │     101.65 │          1 │          0 │             100.07 │ true    │
│         329.0 │               NULL │         28.08 │      77.67 │          1 │          0 │              28.08 │ true    │
│         163.6 │               NULL │         97.68 │     490.68 │          0 │          1 │              163.6 │ true    │
│          62.8 │               NULL │         35.26 │     101.91 │          2 │          0 │              70.52 │ true    │
│          66.1 │               NULL │         34.28 │      95.33 │          2 │          0 │              68.56 │ true    │
│          42.9 │               NULL │          25.5 │       76.5 │          2 │          0 │               51.0 │ true    │
│         102.0 │               NULL │         61.69 │     102.81 │          1 │          0 │              61.69 │ true    │
│         128.6 │               NULL │         23.76 │     160.51 │          2 │          0 │              47.52 │ true    │
│         155.4 │               NULL │         84.59 │      87.95 │          1 │          0 │              84.59 │ true    │
│         284.3 │               NULL │        137.49 │     145.49 │          1 │          0 │             137.49 │ true    │
│         183.8 │               NULL │         70.18 │     237.68 │          2 │          0 │             140.36 │ true    │
│          62.3 │               NULL │         23.14 │      46.28 │          1 │          0 │              23.14 │ true    │
│          69.4 │               NULL │          63.8 │      285.2 │          3 │          1 │ 260.79999999999995 │ true    │
│          89.2 │               NULL │         44.94 │      48.05 │          1 │          0 │              44.94 │ true    │
├───────────────┴────────────────────┴───────────────┴────────────┴────────────┴────────────┴────────────────────┴─────────┤
│ 20 rows                                                                                                        8 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [44]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 신규02, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 신규02  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 5134625 │
│ true    │   63313 │
│ NULL    │ 2167029 │
└─────────┴─────────┘

### 03. 연면적, 용적률 산정 연면적, 대지면적, 건축면적 중 음수 존재

In [48]:
query = """
SELECT
  "대지_면적(㎡)",
  "총괄_대지_면적(㎡)",
  "건축_면적(㎡)",
  "총괄_건축_면적(㎡)",
  "연면적(㎡)",
  "용적_률_산정_연면적(㎡)",
  지상_층_수,
  지하_층_수,
  COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)", 0) < 0
  OR COALESCE("건축_면적(㎡)", "총괄_건축_면적(㎡)", 0) < 0
  OR COALESCE("연면적(㎡)", 0) < 0
  OR COALESCE("지상_층_수", 0) < 0
  OR COALESCE("지하_층_수", 0) < 0
  AS 신규03,
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(5).show()

┌───────────────┬────────────────────┬───────────────┬────────────────────┬────────────┬─────────────────────────┬────────────┬────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 총괄_건축_면적(㎡) │ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 지상_층_수 │ 지하_층_수 │ 신규03  │
│    double     │       double       │    double     │       double       │   double   │         double          │   int32    │   int32    │ boolean │
├───────────────┼────────────────────┼───────────────┼────────────────────┼────────────┼─────────────────────────┼────────────┼────────────┼─────────┤
│          NULL │               NULL │          NULL │               NULL │      29.75 │                    NULL │          1 │          0 │ false   │
│         513.0 │               NULL │        227.82 │               NULL │    1659.98 │                  659.85 │          7 │          1 │ false   │
│          NULL │               NULL │          NULL │               NULL │     169.38 │                    NULL │          2 │          0 │ false   │
│          NULL │               NULL │          NULL │               NULL │      44.33 │                    NULL │          1 │          0 │ false   │
│          NULL │               NULL │          NULL │               NULL │      36.26 │                    NULL │          1 │          0 │ false   │
└───────────────┴────────────────────┴───────────────┴────────────────────┴────────────┴─────────────────────────┴────────────┴────────────┴─────────┘

In [50]:
query = """
SELECT *
FROM
  rel
WHERE
  신규03 = true
"""
con.sql(query).limit(5).show()

┌───────────────┬────────────────────┬───────────────┬────────────────────┬────────────┬─────────────────────────┬────────────┬────────────┬─────────┐
│ 대지_면적(㎡) │ 총괄_대지_면적(㎡) │ 건축_면적(㎡) │ 총괄_건축_면적(㎡) │ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 지상_층_수 │ 지하_층_수 │ 신규03  │
│    double     │       double       │    double     │       double       │   double   │         double          │   int32    │   int32    │ boolean │
├───────────────┼────────────────────┼───────────────┼────────────────────┼────────────┼─────────────────────────┼────────────┼────────────┼─────────┤
│         287.5 │               NULL │         200.0 │               NULL │      657.2 │                  612.96 │          4 │         -1 │ true    │
│         287.5 │               NULL │         200.0 │               NULL │     661.28 │                  617.04 │          4 │         -1 │ true    │
│          NULL │           440375.4 │       5409.27 │          142032.25 │   25167.59 │                19970.66 │          4 │         -1 │ true    │
│         259.2 │               NULL │       125.165 │               NULL │      374.2 │                 242.226 │          2 │         -1 │ true    │
│        3884.0 │               NULL │          NULL │               NULL │      -6.21 │                   -6.21 │          2 │          0 │ true    │
└───────────────┴────────────────────┴───────────────┴────────────────────┴────────────┴─────────────────────────┴────────────┴────────────┴─────────┘

In [49]:
# 컬럼의 값별 개수 집계
con.sql("""
    SELECT 신규03, COUNT(*) AS count
    FROM rel
    GROUP BY ALL
    ORDER BY ALL
""").show()

┌─────────┬─────────┐
│ 신규03  │  count  │
│ boolean │  int64  │
├─────────┼─────────┤
│ false   │ 7364947 │
│ true    │      20 │
└─────────┴─────────┘

### 결과 저장

In [51]:
# save the final result to parquet

query = """
SELECT
  *,
  COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)") < "건축_면적(㎡)" - 1 AS 기존14,
  "연면적(㎡)" < "건축_면적(㎡)" - 1 AS 기존16,
  "건축_면적(㎡)" / "대지_면적(㎡)" * 100 AS 건폐율_재계산,
  ("건폐_율(%)" - 건폐율_재계산) AS 건폐율_차이,
  ABS(건폐율_차이) > 0.1 AS 기존19,
  "용적_률_산정_연면적(㎡)" / "대지_면적(㎡)" * 100 AS 용적률_재계산,
  ("용적_률(%)" - 용적률_재계산) AS 용적률_차이,
  ABS(용적률_차이) > 0.1 AS 기존20,
  "연면적(㎡)" < "용적_률_산정_연면적(㎡)" - 1 AS 신규01,
  ("건축_면적(㎡)" * 지상_층_수) + (COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)") * 지하_층_수) AS 연면적_상한,
  "연면적(㎡)" > 연면적_상한 + 1 AS 신규02,
  COALESCE("대지_면적(㎡)", "총괄_대지_면적(㎡)", 0) < 0
  OR COALESCE("건축_면적(㎡)", "총괄_건축_면적(㎡)", 0) < 0
  OR COALESCE("연면적(㎡)", 0) < 0
  OR COALESCE("지상_층_수", 0) < 0
  OR COALESCE("지하_층_수", 0) < 0
  AS 신규03,
FROM
  rel_orig
"""
rel = con.sql(query)
rel.limit(20).show()
rel.to_parquet("../data/processed/주건축물_검증규칙.parquet")

┌────────────────────┬─────────────────────────┬─────────┬─────────────────────────────────────┬─────────────┬─────────────┬──────────────┬───────────────────┬──────────────────────────────────────┬───────────────┬───────────────┬────────────┬────────────┬─────────────────────────┬────────────┬─────────┬────────────┬────────────┬─────────────┬────────────────────┬────────────────────┬─────────────────┬─────────────────┬──────────────────────────────┬─────────────────┬───────────────────┬─────────┬─────────┬────────────────────┬────────────────────────┬─────────┬────────────────────┬───────────────────────┬─────────┬─────────┬─────────────┬─────────┬─────────┐
│ 관리_건축물대장_PK │ 관리_상위_건축물대장_PK │  단독   │              대지_위치              │ 시군구_코드 │ 법정동_코드 │ 주_용도_코드 │  주_용도_코드_명  │              기타_용도               │ 대지_면적(㎡) │ 건축_면적(㎡) │ 건폐_율(%) │ 연면적(㎡) │ 용적_률_산정_연면적(㎡) │ 용적_률(%) │ 높이(m) │ 지상_층_수 │ 지하_층_수 │ 사용승인_일 │ 총괄_대지_면적(㎡) │ 총괄_건축_면적(㎡) │ 총괄_건폐_율(%) │ 총괄_연면적(㎡) │ 총괄_용적_률_산정_연면적(㎡) │ 총괄_용적_률(%) │ 총괄_주_건축물_수 │ 기존14  │ 기존16  │   건폐율_재계산    │      건폐율_차이       │ 기존19  │   용적률_재계산    │      용적률_차이      │ 기존20  │ 신규01  │ 연면적_상한 │ 신규02  │ 신규03  │
│      varchar       │         varchar         │ boolean │               varchar               │   varchar   │   varchar   │   varchar    │      varchar      │               varchar                │    double     │    double     │   double   │   double   │         double          │   double   │ double  │   int32    │   int32    │   varchar   │       double       │       double       │     double      │     double      │            double            │     double      │       int32       │ boolean │ boolean │       double       │         double         │ boolean │       double       │        double         │ boolean │ boolean │   double    │ boolean │ boolean │
├────────────────────┼─────────────────────────┼─────────┼─────────────────────────────────────┼─────────────┼─────────────┼──────────────┼───────────────────┼──────────────────────────────────────┼───────────────┼───────────────┼────────────┼────────────┼─────────────────────────┼────────────┼─────────┼────────────┼────────────┼─────────────┼────────────────────┼────────────────────┼─────────────────┼─────────────────┼──────────────────────────────┼─────────────────┼───────────────────┼─────────┼─────────┼────────────────────┼────────────────────────┼─────────┼────────────────────┼───────────────────────┼─────────┼─────────┼─────────────┼─────────┼─────────┤
│ 10021950           │ 10021363                │ false   │ 서울특별시 종로구 숭인동 201번지    │ 11110       │ 17500       │ 01000        │ 단독주택          │ 주택                                 │          NULL │          NULL │       NULL │      29.75 │                    NULL │       NULL │    NULL │          1 │          0 │ NULL        │               NULL │               NULL │            NULL │           99.17 │                         NULL │            NULL │                 3 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021957           │ 10021366                │ false   │ 서울특별시 종로구 숭인동 569번지    │ 11110       │ 17500       │ 02000        │ 공동주택          │ 아파트                               │         513.0 │        227.82 │       44.4 │    1659.98 │                  659.85 │     281.04 │    20.6 │          7 │          1 │ 20001129    │               NULL │               NULL │            NULL │         2507.04 │                         NULL │            NULL │                 4 │ false   │ false   │ 44.409356725146196 │  -0.009356725146197675 │ false   │ 128.62573099415204 │    152.41426900584798 │ true    │ false   │     2107.74 │ false   │ false   │
│ 10021958           │ 10021366                │ false   │ 서울특별시 종로구 숭인동 569번지    │ 11110       │ 17500       │ 02000        │ 공동주택          │ 연립주택                             │          NULL │          NULL │       NULL │     169.38 │                    NULL │       NULL │    NULL │          2 │          0 │ 19760702    │               NULL │               NULL │            NULL │         2507.04 │                         NULL │            NULL │                 4 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021973           │ 10021373                │ false   │ 서울특별시 종로구 숭인동 1132번지   │ 11110       │ 17500       │ 04000        │ 제2종근린생활시설 │ 영업                                 │          NULL │          NULL │       NULL │      44.33 │                    NULL │       NULL │    NULL │          1 │          0 │ 19690930    │               NULL │               NULL │            NULL │           80.59 │                         NULL │            NULL │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021974           │ 10021373                │ false   │ 서울특별시 종로구 숭인동 1132번지   │ 11110       │ 17500       │ 04000        │ 제2종근린생활시설 │ 근린생활시설                         │          NULL │          NULL │       NULL │      36.26 │                    NULL │       NULL │    NULL │          1 │          0 │ 19600210    │               NULL │               NULL │            NULL │           80.59 │                         NULL │            NULL │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021980           │ 10021376                │ false   │ 서울특별시 종로구 숭인동 1419번지   │ 11110       │ 17500       │ 04000        │ 제2종근린생활시설 │ 근린생활시설, 근린생활시설(판매시설) │          NULL │          NULL │       NULL │    1411.34 │                    NULL │       NULL │    NULL │          5 │          1 │ 19831117    │               NULL │               NULL │            NULL │         1880.27 │                         NULL │            NULL │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021981           │ 10021377                │ false   │ 서울특별시 종로구 숭인동 1423번지   │ 11110       │ 17500       │ 07000        │ 판매시설          │ 점포                                 │          NULL │          NULL │       NULL │    1190.55 │                    NULL │       NULL │    NULL │          3 │          0 │ 19680726    │               NULL │               NULL │            NULL │          1428.9 │                         NULL │            NULL │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 10021991           │ 10021380                │ false   │ 서울특별시 종로구 평창동 533-4번지  │ 11110       │ 18300       │ 01000        │ 단독주택          │ 다가구용 단독주택(2가구)             │          NULL │        136.18 │       NULL │     314.84 │                  236.47 │       NULL │     7.0 │          2 │          1 │ 19950926    │              658.0 │              183.2 │           27.84 │          361.86 │                       283.49 │           43.08 │                 2 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │      930.36 │ false   │ false   │
│ 10021998           │ 10021383                │ false   │ 서울특별시 종로구 구기동 150번지    │ 11110       │ 18200       │ 02000        │ 공동주택          │ 연립주택                             │          NULL │          NULL │       NULL │    2810.43 │                    NULL │       NULL │    NULL │          3 │          1 │ 19920817    │               NULL │               NULL │            NULL │         5187.37 │                         NULL │            NULL │                 4 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 100211003          │ 10021385                │ false   │ 서울특별시 종로구 부암동 129-10번지 │ 11110       │ 18400       │ 02000        │ 공동주택          │ 공동주택,다세대주택                  │          NULL │        141.82 │       NULL │     693.41 │                  531.52 │       NULL │    15.6 │          4 │          1 │ 20030617    │              793.0 │             457.42 │           57.68 │         2285.58 │                      1632.33 │          205.84 │                 3 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │     1360.28 │ false   │ false   │
│ 100211006          │ 10021386                │ false   │ 서울특별시 종로구 평창동 180-2번지  │ 11110       │ 18300       │ 06000        │ 종교시설          │ 문화및집회시설                       │          NULL │        120.47 │       NULL │      267.8 │                  184.58 │       NULL │     6.7 │          2 │          1 │ 19890919    │              624.0 │             254.84 │           40.84 │          500.65 │                       390.95 │           62.65 │                 2 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │      864.94 │ false   │ false   │
│ 100211007          │ 10021386                │ false   │ 서울특별시 종로구 평창동 180-2번지  │ 11110       │ 18300       │ 04000        │ 제2종근린생활시설 │ 사찰                                 │          NULL │        126.81 │       NULL │     232.85 │                  198.81 │       NULL │     7.8 │          2 │          0 │ 19680821    │              624.0 │             254.84 │           40.84 │          500.65 │                       390.95 │           62.65 │                 2 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │      253.62 │ false   │ false   │
│ 100211014          │ 10021390                │ false   │ 서울특별시 종로구 구기동 10-5번지   │ 11110       │ 18200       │ 01000        │ 단독주택          │ 주택                                 │          NULL │         66.12 │       NULL │     126.96 │                  126.96 │       NULL │     6.2 │          2 │          0 │ 20030728    │             945.92 │             282.93 │           29.91 │          712.46 │                       533.95 │           56.45 │                 4 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │      132.24 │ false   │ false   │
│ 100211015          │ 10021390                │ false   │ 서울특별시 종로구 구기동 10-5번지   │ 11110       │ 18200       │ 03000        │ 제1종근린생활시설 │ 제1종근린생활시설                    │          NULL │         100.7 │       NULL │     380.18 │                   201.4 │       NULL │    5.28 │          2 │          1 │ 20030418    │             945.92 │             282.93 │           29.91 │          712.46 │                       533.95 │           56.45 │                 4 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │     1147.32 │ false   │ false   │
│ 100211017          │ 10021391                │ false   │ 서울특별시 종로구 효제동 160-1번지  │ 11110       │ 16200       │ 18000        │ 창고시설          │ 창고시설                             │          NULL │        151.96 │       NULL │    1147.64 │                 1147.64 │       NULL │    25.7 │          8 │          0 │ 20030822    │              608.0 │             364.26 │           59.91 │          2813.1 │                      2387.83 │          392.74 │                 2 │ false   │ false   │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ false   │     1215.68 │ false   │ false   │
│ 100211019          │ 10021392                │ false   │ 서울특별시 종로구 구기동 10-18번지  │ 11110       │ 18200       │ 02000        │ 공동주택          │ 공동주택,다세대주택                  │          NULL │          NULL │       NULL │     297.27 │                    NULL │       NULL │     7.9 │          2 │          2 │ 20030905    │              983.0 │             290.99 │            29.6 │         1221.89 │                       549.48 │            55.9 │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 100211020          │ 10021392                │ false   │ 서울특별시 종로구 구기동 10-18번지  │ 11110       │ 18200       │ 02000        │ 공동주택          │ 공동주택,다세대주택                  │          NULL │          NULL │       NULL │     924.62 │                    NULL │       NULL │     7.9 │          2 │          2 │ 20030905    │              983.0 │             290.99 │            29.6 │         1221.89 │                       549.48 │            55.9 │                 2 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 100211025          │ 10021393                │ false   │ 서울특별시 종로구 창신동 702번지    │ 11110       │ 17400       │ 02000        │ 공동주택          │ 공동주택(아파트)                     │       24923.1 │          NULL │       NULL │   11443.68 │                    NULL │       NULL │    NULL │         14 │          1 │ 19921125    │            24923.1 │               NULL │            NULL │        59593.68 │                         NULL │            NULL │                 6 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 100211026          │ 10021393                │ false   │ 서울특별시 종로구 창신동 702번지    │ 11110       │ 17400       │ 07000        │ 판매시설          │ 판매시설,종교시설                    │       24923.1 │          NULL │       NULL │    3221.71 │                    NULL │       NULL │    NULL │          4 │          1 │ 19921125    │            24923.1 │               NULL │            NULL │        59593.68 │                         NULL │            NULL │                 6 │ NULL    │ NULL    │               NULL │                   NULL │ NULL    │               NULL │                  NULL │ NULL    │ NULL    │        NULL │ NULL    │ false   │
│ 100211032          │ 10021396                │ false   │ 서울특별시 종로구 인의동 50-2번지   │ 11110       │ 15700       │ 03000        │ 제1종근린생활시설 │ 근린생활시설                         │        614.52 │        338.25 │      55.04 │    2025.42 │                 1687.41 │     274.59 │    17.3 │          5 │          1 │ 19821012    │             614.52 │             338.25 │           55.04 │         2045.25 │                      1687.41 │          274.59 │                 2 │ false   │ false   │  55.04296035930483 │ -0.0029603593048292964 │ false   │ 274.58992384299944 │ 7.615700053520413e-05 │ false   │ false   │     2305.77 │ false   │ false   │
├────────────────────┴─────────────────────────┴─────────┴─────────────────────────────────────┴─────────────┴─────────────┴──────────────┴───────────────────┴──────────────────────────────────────┴───────────────┴───────────────┴────────────┴────────────┴─────────────────────────┴────────────┴─────────┴────────────┴────────────┴─────────────┴────────────────────┴────────────────────┴─────────────────┴─────────────────┴──────────────────────────────┴─────────────────┴───────────────────┴─────────┴─────────┴────────────────────┴────────────────────────┴─────────┴────────────────────┴───────────────────────┴─────────┴─────────┴─────────────┴─────────┴─────────┤
│ 20 rows                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      38 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘